`timescale 1ns/1ps
// Auto-generated by gen_spike_bitstream.py - Phase-0 silicon-Fmax spike.
// Reset-on-arm: the stimulus counter and both DUTs are held in reset until the
// logic analyzer asserts `cap`, so every capture starts at counter phase 0
// (capture == golden[0:N] up to a small fixed registration shift).
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        cap,
    input  wire [5:0]  sel,
    output reg  [15:0] probe
);
    wire dut_rst_n = rst_n & cap;
    reg [31:0] cnt;
    always @(posedge clk)
        if (!rst_n || !cap) cnt <= 32'b0;
        else                cnt <= cnt + 1'b1;

    wire [15:0] fir_y;
    wire [15:0] echo_y;

    fir16_8b u_fir  ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(fir_y)  );
    echo8b   u_echo ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(echo_y) );

    always @(*) begin
        case (sel)
            6'd0:    probe = fir_y;
            6'd1:    probe = echo_y;
            default: probe = 16'b0;
        endcase
    end
endmodule
