`timescale 1ns/1ps
// Auto-generated by gen_catalog_bitstream.py - Phase-2 silicon-Fmax-at-scale.
// Reset-on-arm: stimulus counter + all DUTs held in reset until `cap`.
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        cap,
    input  wire [5:0]  sel,
    output reg  [15:0] probe
);
    wire dut_rst_n = rst_n & cap;
    reg [31:0] cnt;
    always @(posedge clk)
        if (!rst_n || !cap) cnt <= 32'b0;
        else                cnt <= cnt + 1'b1;

    wire [15:0] y0;
    wire [15:0] y1;
    wire [15:0] y2;
    wire [15:0] y3;
    wire [15:0] y4;
    wire [15:0] y5;

    fir8_8b u0 ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y0) );
    fir16_8b u1 ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y1) );
    fir32_8b u2 ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y2) );
    poly4_8b u3 ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y3) );
    poly6_8b u4 ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y4) );
    echo8b u5 ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y5) );

    always @(*) begin
        case (sel)
            6'd0: probe = y0;
            6'd1: probe = y1;
            6'd2: probe = y2;
            6'd3: probe = y3;
            6'd4: probe = y4;
            6'd5: probe = y5;
            default: probe = 16'b0;
        endcase
    end
endmodule
