#!/usr/bin/env python3
"""
gen_bitstream.py  -  Batch the design catalog into synthesizable bitstreams.

A PYNQ-Z2 (Zynq-7020) cannot hold 1000+ DUTs + a 1000-way probe mux in one
bitstream. So designs are split into batches (default 64). For each batch this
emits a self-contained `dut_top_b{K}.v` that:
  - instantiates that batch's DUTs with counter-driven inputs
  - renames every DUT's internal wires with a per-instance prefix (DUTs share
    generic names like `count`/`out`/`result` that would otherwise collide)
  - muxes the selected DUT's packed 16-bit value onto `probe` via local `sel`

It also writes:
  rtl/batches/batch_manifest.json   global sel<->design map + probe masks/periods
  rtl/batches/build_b{K}.tcl        headless Vivado build script per batch

The Tcl is self-contained (project flow): it adds la_axi_wide.v + dut_top_b{K}.v
+ the batch's design.v files, builds the Zynq PS7 + AXI-Lite -> la_axi_wide ->
dut_top block design inline, then runs synth -> impl -> write_bitstream and
copies out system_b{K}.bit + .hwh. Paths derive from the script location so it
runs on Windows or Linux with no edits.

Usage:
    python gen_bitstream.py                 # default batch size 64
    python gen_bitstream.py --batch 48
"""

import os
import re
import json
import argparse

ROOT = os.path.dirname(os.path.abspath(__file__))
RTL_LIB = os.path.join(ROOT, "rtl_library")
OUT_DIR = os.path.join(ROOT, "rtl", "batches")


def wire_names(outwires):
    """Extract declared identifiers from a list of 'wire [..] a, b;' decls."""
    names = []
    for decl in outwires:
        body = decl.strip().rstrip(";")
        body = re.sub(r"^\s*(wire|reg|signed|\s)+", "", body)  # strip qualifiers
        body = re.sub(r"\[[^\]]*\]", "", body)   # drop width
        for tok in body.split(","):
            tok = tok.strip()
            if tok:
                names.append(tok)
    return names


def rename(text, mapping):
    """Whole-word rename of wire identifiers in a code/expr string."""
    def repl(m):
        return mapping.get(m.group(0), m.group(0))
    return re.sub(r"\b\w+\b", repl, text)


def emit_batch(batch_id, recs):
    sw = max(1, (len(recs) - 1).bit_length())
    insts, decls, cases = [], [], []
    for local_sel, rec in enumerate(recs):
        pfx = f"d{local_sel}_"
        names = wire_names(rec["outwires"])
        mp = {n: pfx + n for n in names}

        for decl in rec["outwires"]:
            decls.append("    " + rename(decl, mp))

        # rename only the connected signal inside each .port(signal), never the
        # port identifier itself.
        ports = re.sub(r"(\.\w+\s*\()([^)]*)(\))",
                       lambda m: m.group(1) + rename(m.group(2), mp) + m.group(3),
                       rec["ports"])
        insts.append(
            f"    {rec['name']} u_{pfx[:-1]} ( .clk(clk), .rst_n(rst_n), {ports} );"
        )
        probe = rename(rec["probe"], mp)
        cases.append(f"            {sw}'d{local_sel}: probe = {probe};")

    body = f"""`timescale 1ns/1ps
// Auto-generated by gen_bitstream.py  -  batch {batch_id} ({len(recs)} DUTs).
// Local sel[{sw-1}:0] selects which DUT drives probe[15:0].
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [{sw-1}:0] sel,
    output reg  [15:0] probe
);
    // free-running counter -- deterministic stimulus source (matches scorer tb)
    reg [31:0] cnt;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) cnt <= 32'b0;
        else        cnt <= cnt + 1'b1;

{chr(10).join(decls)}

{chr(10).join(insts)}

    always @(*) begin
        case (sel)
{chr(10).join(cases)}
            default: probe = 16'b0;
        endcase
    end
endmodule
"""
    with open(os.path.join(OUT_DIR, f"dut_top_b{batch_id}.v"), "w") as f:
        f.write(body)

    # Self-contained headless Vivado build (project flow) for this batch.
    # Portable: all paths derive from the script's own location, so it runs on
    # Windows or Linux. The block design (Zynq PS7 + AXI-Lite -> la_axi_wide ->
    # dut_top) is built inline -- no external BD_TCL needed. Reuses the exact
    # PS7 board-preset automation proven in the project's synthesis flow.
    design_files = " \\\n    ".join(
        f"[file join $RTL_LIB {r['name']} design.v]" for r in recs)
    tcl = f"""# Auto-generated by gen_bitstream.py  -  batch {batch_id} (self-contained).
# Build:  vivado -mode batch -source build_b{batch_id}.tcl
set BATCH   {batch_id}
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b{batch_id}]
file mkdir $OUT

create_project sys_b{batch_id} [file join $OUT proj] -part $PART -force
add_files [list \\
    [file join $ROOT rtl la_axi_wide.v] \\
    [file join $ROOT rtl batches dut_top_b{batch_id}.v] \\
    {design_files} ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {{make_external "FIXED_IO, DDR" apply_board_preset "1"}} \\
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \\
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \\
    -config {{Master "/ps7/M_AXI_GP0" Clk "Auto"}} \\
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \\
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \\
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \\
    [file join $OUT system_b{batch_id}.bit]
set hwh [glob -nocomplain \\
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \\
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {{$hwh ne ""}} {{
    file copy -force [lindex $hwh 0] [file join $OUT system_b{batch_id}.hwh]
}}
puts "BATCH {batch_id} DONE -> [file join $OUT system_b{batch_id}.bit]"
"""
    with open(os.path.join(OUT_DIR, f"build_b{batch_id}.tcl"), "w") as f:
        f.write(tcl)

    return sw


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--batch", type=int, default=64)
    args = ap.parse_args()

    with open(os.path.join(RTL_LIB, "manifest.json")) as f:
        manifest = json.load(f)
    os.makedirs(OUT_DIR, exist_ok=True)

    batches = [manifest[i:i + args.batch]
               for i in range(0, len(manifest), args.batch)]

    global_map = []
    for k, recs in enumerate(batches):
        sw = emit_batch(k, recs)
        for local_sel, rec in enumerate(recs):
            global_map.append({
                "global_sel": rec["sel"],
                "batch": k,
                "local_sel": local_sel,
                "name": rec["name"],
                "family": rec["family"],
                "probe_mask": rec["probe_mask"],
                "period": rec["period"],
            })
        print(f"batch {k:2d}: {len(recs):3d} designs, sel width {sw}")

    with open(os.path.join(OUT_DIR, "batch_manifest.json"), "w") as f:
        json.dump({"batch_size": args.batch, "n_batches": len(batches),
                   "designs": global_map}, f, indent=1)
    print(f"\n{len(manifest)} designs -> {len(batches)} bitstreams "
          f"(batch size {args.batch}).")
    print(f"Wrote dut_top_bK.v + build_bK.tcl + batch_manifest.json to {OUT_DIR}")


if __name__ == "__main__":
    main()
