#!/usr/bin/env python3
"""
gen_spike_bitstream.py  -  Phase-0 silicon-Fmax FEASIBILITY SPIKE bitstream.

Packs exactly two DUTs into one reset-on-arm dut_top:
  sel 0 = fir16_8b   (design under test: deep multiply-accumulate critical path)
  sel 1 = echo8b     (canary: pure flip-flop chain, no logic between registers)

Both are clocked by the PS fabric clock (FCLK0).  The whole point of the spike
is to over-clock at RUNTIME (pynq Clocks.fclk0_mhz) and find the frequency at
which the FIR diverges from its golden -- the silicon Fmax.  The canary, which
shares the sel-mux -> LA-buffer -> AXI-readback tail, must keep matching its
golden well past the FIR's failure point; if it doesn't, we are measuring the
capture harness, not the FIR (see clock_sweep_fmax.py's GATE).

This reuses the exact reset-on-arm dut_top + headless-Vivado structure of
gen_candidate_bitstream.py, but with a fixed 2-DUT payload and the reference
design.v files (plain Verilog-2001) instead of renamed SystemVerilog candidates.

Usage (anywhere with the repo):
    python gen_spike_bitstream.py
Then on the laptop (Vivado on PATH):
    vivado -mode batch -source rtl/spike/build_spike.tcl
Build constrains timing at 100 MHz; the board sweep over-clocks from there.
For the Vivado STA Fmax (the ratio denominator) run separately:
    python run_ppa.py --dir rtl_library/fir16_8b --out rtl/spike/fir_sta.jsonl \
        --clk clk --period 5.0     # 5.0 ns = tight 200 MHz target to read true WNS
"""

import os

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(ROOT, "rtl", "spike")

# (sel, module, design_dir, port_map, probe_expr, probe_mask)
DUTS = [
    (0, "fir16_8b", "fir16_8b", ".x(cnt[7:0]), .y(fir_y)", "fir_y", 0xFFFF),
    (1, "echo8b",   "echo8b",   ".x(cnt[7:0]), .y(echo_y)", "echo_y", 0xFFFF),
]

DUT_TOP = """`timescale 1ns/1ps
// Auto-generated by gen_spike_bitstream.py - Phase-0 silicon-Fmax spike.
// Reset-on-arm: the stimulus counter and both DUTs are held in reset until the
// logic analyzer asserts `cap`, so every capture starts at counter phase 0
// (capture == golden[0:N] up to a small fixed registration shift).
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        cap,
    input  wire [5:0]  sel,
    output reg  [15:0] probe
);
    wire dut_rst_n = rst_n & cap;
    reg [31:0] cnt;
    always @(posedge clk)
        if (!rst_n || !cap) cnt <= 32'b0;
        else                cnt <= cnt + 1'b1;

    wire [15:0] fir_y;
    wire [15:0] echo_y;

    fir16_8b u_fir  ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(fir_y)  );
    echo8b   u_echo ( .clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(echo_y) );

    always @(*) begin
        case (sel)
            6'd0:    probe = fir_y;
            6'd1:    probe = echo_y;
            default: probe = 16'b0;
        endcase
    end
endmodule
"""

BUILD_TCL = """# Auto-generated - Phase-0 silicon-Fmax spike (self-contained).
set PART    "xc7z020clg400-1"
set CLK_MHZ 100
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set OUT     [file join $ROOT rtl spike out]
file mkdir $OUT

create_project sys_spike [file join $OUT proj] -part $PART -force
add_files [list \\
    [file join $ROOT rtl la_axi_wide.v] \\
    [file join $ROOT rtl spike dut_top_spike.v] \\
    [file join $ROOT rtl_library fir16_8b design.v] \\
    [file join $ROOT rtl_library echo8b design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \\
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \\
    [get_bd_cells ps7]
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \\
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \\
    [get_bd_intf_pins la0/S_AXI]
connect_bd_net [get_bd_pins la0/sel]       [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]     [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins la0/capturing] [get_bd_pins dut0/cap]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]
assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \\
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \\
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \\
    [file join $OUT system_spike.bit]
set hwh [glob -nocomplain \\
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \\
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_spike.hwh]
}
puts "SPIKE BITSTREAM DONE"
"""


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "dut_top_spike.v"), "w") as f:
        f.write(DUT_TOP)
    with open(os.path.join(OUT_DIR, "build_spike.tcl"), "w") as f:
        f.write(BUILD_TCL)
    print("wrote:")
    print("  rtl/spike/dut_top_spike.v   (FIR sel=0, canary sel=1, reset-on-arm)")
    print("  rtl/spike/build_spike.tcl   (Vivado: vivado -mode batch -source ...)")
    print("\nDUT map for the sweep:")
    for sel, mod, _d, _pm, _pe, mask in DUTS:
        print(f"  sel {sel}: {mod:10s} probe_mask={mask:#06x}")
    print("\nnext:")
    print("  laptop: vivado -mode batch -source rtl/spike/build_spike.tcl")
    print("  board : sudo /usr/local/share/pynq-venv/bin/python3 clock_sweep_fmax.py "
          "--bit rtl/spike/out/system_spike.bit")


if __name__ == "__main__":
    main()
