#!/usr/bin/env python3
"""
gen_catalog_bitstream.py  -  Phase-2 silicon-Fmax-at-scale bitstream.

Packs the whole accelerator catalog + the canary into ONE reset-on-arm dut_top,
each on its own sel, all driven by x=cnt[7:0]:

  sel 0 fir8_8b   sel 1 fir16_8b  sel 2 fir32_8b
  sel 3 poly4_8b  sel 4 poly6_8b  sel 5 echo8b (canary)

Uses la_axi_fast (DEPTH=2048) -- the slim LA that lifted the capture-harness
ceiling past 200 MHz in Phase 0 -- and constrains the build at 200 MHz so the
harness is optimised across the whole sweep range (the slow DUTs will not meet
200; that is the point, we over-clock and find where each breaks).

Usage (anywhere with the repo):
    python gen_catalog_bitstream.py
Then laptop (Vivado):
    "<vivado.bat>" -mode batch -source rtl/catalog/build_catalog.tcl
Then board:
    sudo /usr/local/share/pynq-venv/bin/python3 sweep_catalog.py \
        --bit rtl/catalog/out/system_catalog.bit
"""

import os
import json

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "rtl", "catalog")

# sel -> (module/design dir name, role).  All share .x(cnt[7:0]) .y(16-bit).
# The unpipelined reference designs (rtl_library/<name>/design.v); the canary
# (echo8b) certifies per design that the measured Fmax is the DUT's, not the rig.
DUTS = [
    (0,  "fir8_8b",   "dut"),
    (1,  "fir12_8b",  "dut"),
    (2,  "fir16_8b",  "dut"),
    (3,  "fir24_8b",  "dut"),
    (4,  "fir32_8b",  "dut"),
    (5,  "poly3_8b",  "dut"),
    (6,  "poly4_8b",  "dut"),
    (7,  "poly5_8b",  "dut"),
    (8,  "poly6_8b",  "dut"),
    (9,  "poly8_8b",  "dut"),
    (10, "cordic8",   "dut"),
    (11, "cordic12",  "dut"),
    (12, "cordic16",  "dut"),
    (13, "echo8b",    "canary"),
]


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    wires = "\n".join(f"    wire [15:0] y{sel};" for sel, _, _ in DUTS)
    insts = "\n".join(
        f"    {name} u{sel} ( .clk(clk), .rst_n(dut_rst_n), "
        f".x(cnt[7:0]), .y(y{sel}) );" for sel, name, _ in DUTS)
    cases = "\n".join(f"            6'd{sel}: probe = y{sel};"
                      for sel, _, _ in DUTS)

    dut_top = f"""`timescale 1ns/1ps
// Auto-generated by gen_catalog_bitstream.py - Phase-2 silicon-Fmax-at-scale.
// Reset-on-arm: stimulus counter + all DUTs held in reset until `cap`.
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        cap,
    input  wire [5:0]  sel,
    output reg  [15:0] probe
);
    wire dut_rst_n = rst_n & cap;
    reg [31:0] cnt;
    always @(posedge clk)
        if (!rst_n || !cap) cnt <= 32'b0;
        else                cnt <= cnt + 1'b1;

{wires}

{insts}

    always @(*) begin
        case (sel)
{cases}
            default: probe = 16'b0;
        endcase
    end
endmodule
"""

    design_files = " \\\n    ".join(
        f"[file join $ROOT rtl_library {name} design.v]"
        for _, name, _ in DUTS)

    build_tcl = f"""# Auto-generated - Phase-2 catalog silicon-Fmax bitstream.
set PART    "xc7z020clg400-1"
set CLK_MHZ 200
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set OUT     [file join $ROOT rtl catalog out]
file mkdir $OUT

create_project sys_catalog [file join $OUT proj] -part $PART -force
add_files [list \\
    [file join $ROOT rtl la_axi_fast.v] \\
    [file join $ROOT rtl catalog dut_top_catalog.v] \\
    {design_files} ]
update_compile_order -fileset sources_1

create_bd_design "system"
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {{make_external "FIXED_IO, DDR" apply_board_preset "1"}} \\
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \\
    [get_bd_cells ps7]
create_bd_cell -type module -reference la_axi_fast la0
create_bd_cell -type module -reference dut_top      dut0
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \\
    -config {{Master "/ps7/M_AXI_GP0" Clk "Auto"}} \\
    [get_bd_intf_pins la0/S_AXI]
connect_bd_net [get_bd_pins la0/sel]       [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]     [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins la0/capturing] [get_bd_pins dut0/cap]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]
assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \\
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \\
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \\
    [file join $OUT system_catalog.bit]
set hwh [glob -nocomplain \\
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \\
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {{$hwh ne ""}} {{
    file copy -force [lindex $hwh 0] [file join $OUT system_catalog.hwh]
}}
puts "CATALOG BITSTREAM DONE"
"""

    sels = {name: {"sel": sel, "role": role} for sel, name, role in DUTS}

    with open(os.path.join(OUT_DIR, "dut_top_catalog.v"), "w") as f:
        f.write(dut_top)
    with open(os.path.join(OUT_DIR, "build_catalog.tcl"), "w") as f:
        f.write(build_tcl)
    with open(os.path.join(OUT_DIR, "catalog_sels.json"), "w") as f:
        json.dump(sels, f, indent=1)

    print("wrote rtl/catalog/{dut_top_catalog.v, build_catalog.tcl, "
          "catalog_sels.json}")
    for sel, name, role in DUTS:
        print(f"  sel {sel}: {name:10s} ({role})")
    print("\nnext: build_catalog.tcl on the laptop, then sweep_catalog.py on the board")


if __name__ == "__main__":
    main()
