#!/usr/bin/env python3
"""
gen_bitstream.py  -  Batch the design catalog into synthesizable bitstreams.

A PYNQ-Z2 (Zynq-7020) cannot hold 1000+ DUTs + a 1000-way probe mux in one
bitstream. So designs are split into batches (default 64). For each batch this
emits a self-contained `dut_top_b{K}.v` that:
  - instantiates that batch's DUTs with counter-driven inputs
  - renames every DUT's internal wires with a per-instance prefix (DUTs share
    generic names like `count`/`out`/`result` that would otherwise collide)
  - muxes the selected DUT's packed 16-bit value onto `probe` via local `sel`

It also writes:
  rtl/batches/batch_manifest.json   global sel<->design map + probe masks/periods
  rtl/batches/build_b{K}.tcl        headless Vivado build script per batch

The Tcl is a non-project-flow template: it reads la_axi.v + dut_top_b{K}.v + the
batch's design.v files, sources the user's PS/AXI block-design hook, then runs
synth -> impl -> write_bitstream. Fill in PART and BD_TCL once (see top of Tcl).

Usage:
    python gen_bitstream.py                 # default batch size 64
    python gen_bitstream.py --batch 48
"""

import os
import re
import json
import argparse

ROOT = os.path.dirname(os.path.abspath(__file__))
RTL_LIB = os.path.join(ROOT, "rtl_library")
OUT_DIR = os.path.join(ROOT, "rtl", "batches")


def wire_names(outwires):
    """Extract declared identifiers from a list of 'wire [..] a, b;' decls."""
    names = []
    for decl in outwires:
        body = decl.strip().rstrip(";")
        body = re.sub(r"^\s*(wire|reg|signed|\s)+", "", body)  # strip qualifiers
        body = re.sub(r"\[[^\]]*\]", "", body)   # drop width
        for tok in body.split(","):
            tok = tok.strip()
            if tok:
                names.append(tok)
    return names


def rename(text, mapping):
    """Whole-word rename of wire identifiers in a code/expr string."""
    def repl(m):
        return mapping.get(m.group(0), m.group(0))
    return re.sub(r"\b\w+\b", repl, text)


def emit_batch(batch_id, recs):
    sw = max(1, (len(recs) - 1).bit_length())
    insts, decls, cases = [], [], []
    for local_sel, rec in enumerate(recs):
        pfx = f"d{local_sel}_"
        names = wire_names(rec["outwires"])
        mp = {n: pfx + n for n in names}

        for decl in rec["outwires"]:
            decls.append("    " + rename(decl, mp))

        # rename only the connected signal inside each .port(signal), never the
        # port identifier itself.
        ports = re.sub(r"(\.\w+\s*\()([^)]*)(\))",
                       lambda m: m.group(1) + rename(m.group(2), mp) + m.group(3),
                       rec["ports"])
        insts.append(
            f"    {rec['name']} u_{pfx[:-1]} ( .clk(clk), .rst_n(rst_n), {ports} );"
        )
        probe = rename(rec["probe"], mp)
        cases.append(f"            {sw}'d{local_sel}: probe = {probe};")

    body = f"""`timescale 1ns/1ps
// Auto-generated by gen_bitstream.py  -  batch {batch_id} ({len(recs)} DUTs).
// Local sel[{sw-1}:0] selects which DUT drives probe[15:0].
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [{sw-1}:0] sel,
    output reg  [15:0] probe
);
    // free-running counter -- deterministic stimulus source (matches scorer tb)
    reg [31:0] cnt;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) cnt <= 32'b0;
        else        cnt <= cnt + 1'b1;

{chr(10).join(decls)}

{chr(10).join(insts)}

    always @(*) begin
        case (sel)
{chr(10).join(cases)}
            default: probe = 16'b0;
        endcase
    end
endmodule
"""
    with open(os.path.join(OUT_DIR, f"dut_top_b{batch_id}.v"), "w") as f:
        f.write(body)

    # Vivado headless build template for this batch.
    design_files = " \\\n    ".join(
        f"$RTL_LIB/{r['name']}/design.v" for r in recs)
    tcl = f"""# Auto-generated headless Vivado build  -  batch {batch_id}.
# ---- fill these in once for your board/project ----
set PART   "xc7z020clg400-1"        ;# PYNQ-Z2 part
set BD_TCL "$::env(HOME)/pynq_bd.tcl";# your block design (Zynq PS + AXI + la_axi) hook
# ---------------------------------------------------
set ROOT   "{ROOT}"
set RTL_LIB "{RTL_LIB}"
set OUT    "$ROOT/rtl/batches/out_b{batch_id}"
file mkdir $OUT

create_project -in_memory -part $PART
read_verilog $ROOT/rtl/la_axi.v
read_verilog $ROOT/rtl/batches/dut_top_b{batch_id}.v
read_verilog {design_files}
# Bring in the Zynq PS / AXI / la_axi block design + top wrapper:
if {{[file exists $BD_TCL]}} {{ source $BD_TCL }}

# Top is your board wrapper that instantiates dut_top + la_axi + PS.
synth_design -top design_1_wrapper -part $PART
opt_design
place_design
route_design
write_bitstream -force $OUT/system_b{batch_id}.bit
write_hw_platform -fixed -force $OUT/system_b{batch_id}.xsa
puts "BATCH {batch_id} DONE -> $OUT/system_b{batch_id}.bit"
"""
    with open(os.path.join(OUT_DIR, f"build_b{batch_id}.tcl"), "w") as f:
        f.write(tcl)

    return sw


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--batch", type=int, default=64)
    args = ap.parse_args()

    with open(os.path.join(RTL_LIB, "manifest.json")) as f:
        manifest = json.load(f)
    os.makedirs(OUT_DIR, exist_ok=True)

    batches = [manifest[i:i + args.batch]
               for i in range(0, len(manifest), args.batch)]

    global_map = []
    for k, recs in enumerate(batches):
        sw = emit_batch(k, recs)
        for local_sel, rec in enumerate(recs):
            global_map.append({
                "global_sel": rec["sel"],
                "batch": k,
                "local_sel": local_sel,
                "name": rec["name"],
                "family": rec["family"],
                "probe_mask": rec["probe_mask"],
                "period": rec["period"],
            })
        print(f"batch {k:2d}: {len(recs):3d} designs, sel width {sw}")

    with open(os.path.join(OUT_DIR, "batch_manifest.json"), "w") as f:
        json.dump({"batch_size": args.batch, "n_batches": len(batches),
                   "designs": global_map}, f, indent=1)
    print(f"\n{len(manifest)} designs -> {len(batches)} bitstreams "
          f"(batch size {args.batch}).")
    print(f"Wrote dut_top_bK.v + build_bK.tcl + batch_manifest.json to {OUT_DIR}")


if __name__ == "__main__":
    main()
