#!/usr/bin/env python3
"""
gen_sft_corpus.py  -  V2 Stage 1: build an SFT warm-start corpus of CORRECT,
diverse (spec -> RTL) pairs, every one verified by the V2 oracle.

Why: the cross-model probe showed base models write these accelerators correctly
at ~2% -> RL has no foothold (RL refines competence, can't create it). The fix is
SFT warm-start (the supervisor's own roadmap step 1). This generates the corpus:
for a parameter grid over the single-input accelerator families, emit each design
in MULTIPLE coding styles (unpipelined reference + pipelined), so the model learns
both correctness AND implementation diversity (the diversity that later gives the
silicon-Fmax RL its headroom). Every pair is oracle-verified (I/O-equivalence under
directed+random stimulus) before it enters the corpus -- no incorrect training data.

Output: sft_corpus.jsonl  {"design","family","style","prompt","completion"} per line.
Prompt = natural-language spec + exact module interface; completion = the RTL.

Run anywhere with iverilog:  python gen_sft_corpus.py --out sft_corpus.jsonl
"""

import os
import re
import json
import argparse

import gen_accelerator_catalog as GAC
import oracle

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# FROZEN held-out split (CLAUDE.md §5). Held-out designs must NEVER enter the
# SFT corpus, the GRPO design list, or the surrogate's training rows -- they are
# the ONLY designs Phase-B evaluation is allowed to touch. Two regimes:
#   * interpolation  -- parameters INSIDE the trained grid, held out:
#       fir/firr taps {6,10,18,26}; poly degree 7 (all coefficient variants).
#   * extrapolation  -- parameters OUTSIDE the trained grid (so they are never
#       generated by the train grid at all; eval builds them directly):
#       fir/firr taps {36,40}; poly NEW variants v6,v7 of degrees {4,8}.
# is_holdout() is the single source of truth, imported by grpo_oracle (to drop
# them from the GRPO design list) and eval_holdout (to target only them).
HOLDOUT_FIR_TAPS = {6, 10, 18, 26}      # interpolation (fir and firr)
HOLDOUT_POLY_DEG = {7}                   # interpolation (all poly7 variants)
HOLDOUT_EXTRAP_TAPS = {36, 40}           # extrapolation (fir and firr)
HOLDOUT_EXTRAP_POLY_VARS = {6, 7}        # extrapolation poly variants (deg 4,8)


def is_holdout(name):
    """True if `name` is in the frozen §5 held-out split (interp OR extrap)."""
    m = re.match(r"fir(\d+)_8b$", name)
    if m:
        T = int(m.group(1))
        return T in HOLDOUT_FIR_TAPS or T in HOLDOUT_EXTRAP_TAPS
    m = re.match(r"firr(\d+)$", name)
    if m:
        T = int(m.group(1))
        return T in HOLDOUT_FIR_TAPS or T in HOLDOUT_EXTRAP_TAPS
    m = re.match(r"poly(\d+)_v(\d+)_8b$", name)
    if m:
        D, v = int(m.group(1)), int(m.group(2))
        return D in HOLDOUT_POLY_DEG or v in HOLDOUT_EXTRAP_POLY_VARS
    m = re.match(r"poly(\d+)_8b$", name)          # v0 form (poly{D}_8b)
    if m:
        return int(m.group(1)) in HOLDOUT_POLY_DEG
    return False


def header_of(rtl):
    """Extract the `module ... );` interface block to put in the prompt."""
    m = re.search(r"(?s)(module\s+\w+\s*\(.*?\);)", rtl)
    return m.group(1) if m else ""


def make_prompt(spec, rtl):
    return (spec.rstrip() + "\n\nUse exactly this module interface "
            "(port names and widths must match):\n\n" + header_of(rtl) +
            "\n\nWrite standard synthesizable Verilog-2001. Active-low rst_n "
            "clears the outputs; outputs are registered on posedge clk.")


def designs(exclude_holdout=False):
    """Yield (design_name, family, spec_text, {style: rtl_text}) over a grid.

    Each design is emitted in MULTIPLE oracle-verified correct styles so SFT
    learns implementation diversity (the headroom the silicon-Fmax RL exploits):
      fir/firr : array+loop reference, pipelined, unrolled named-register form
      poly     : combinational Horner chain, pipelined, inline nested form
      cordic   : unrolled combinational chain, pipelined

    exclude_holdout=True drops the frozen §5 held-out designs (is_holdout) so the
    same generator produces the CLEAN train corpus (and, via grpo_oracle, the
    train-only GRPO design list). Extrapolation designs (taps 36/40, poly v6/v7)
    are outside this grid regardless; eval_holdout builds them directly.
    """
    fir_taps = list(range(4, 33))                  # 4..32, every tap count
    for T in fir_taps:
        nm = f"fir{T}_8b"
        if exclude_holdout and is_holdout(nm):
            continue
        c = GAC.fir_coeffs(T)
        yield nm, "fir", GAC.fir_spec(nm, T), {
            "ref": GAC.fir_ref(nm, c), "pipe": GAC.fir_pipe(nm, c),
            "unrolled": GAC.fir_unrolled(nm, c),
            "transposed": GAC.fir_transposed(nm, c)}
    for T in fir_taps:
        nm = f"firr{T}"
        if exclude_holdout and is_holdout(nm):
            continue
        c = [k + 1 for k in range(T)]
        yield nm, "firr", GAC.firr_spec(nm, T), {
            "ref": GAC.fir_ref(nm, c), "pipe": GAC.fir_pipe(nm, c),
            "unrolled": GAC.fir_unrolled(nm, c),
            "transposed": GAC.fir_transposed(nm, c)}
    poly_variants = 6          # distinct coefficient sets per degree (incl. v0)
    for D in range(2, 11):
        for v in range(poly_variants):
            nm = f"poly{D}_8b" if v == 0 else f"poly{D}_v{v}_8b"
            if exclude_holdout and is_holdout(nm):
                continue
            c = GAC.poly_coeffs_var(D, v)
            yield nm, "poly", GAC.poly_spec(nm, D, c), {
                "ref": GAC.poly_ref(nm, c), "pipe": GAC.poly_pipe(nm, c),
                "inline": GAC.poly_inline(nm, c)}
    for N in [6, 8, 10, 12, 14, 16, 18]:
        atan, x0 = GAC.cordic_tables(N); nm = f"cordic{N}"
        yield nm, "cordic", GAC.cordic_spec(nm, N), {
            "ref": GAC.cordic_ref(nm, N, atan, x0),
            "pipe": GAC.cordic_pipe(nm, N, atan, x0)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(HERE, "sft_corpus.jsonl"))
    ap.add_argument("--n", type=int, default=512, help="oracle stimulus length")
    ap.add_argument("--holdout", action="store_true",
                    help="exclude the frozen §5 held-out designs (clean Phase-B "
                         "train corpus; Phase-B always uses this flag)")
    args = ap.parse_args()

    if args.holdout:
        print("[holdout] excluding frozen §5 held-out designs "
              "(interp fir/firr taps 6/10/18/26 + poly deg 7; extrap never in grid)")

    rows, kept, rejected = [], 0, 0
    by_fam = {}
    for name, fam, spec, styles in designs(exclude_holdout=args.holdout):
        for style, rtl in styles.items():
            try:
                r = oracle.score(rtl, name, n=args.n)
            except Exception as e:
                print(f"  [skip] {name}/{style}: {e}")
                rejected += 1
                continue
            if not r["correct"]:
                print(f"  [REJECT] {name}/{style}: match={r['match']} "
                      f"compiled={r['compiled']} (oracle gate)")
                rejected += 1
                continue
            rows.append({"design": name, "family": fam, "style": style,
                         "prompt": make_prompt(spec, rtl), "completion": rtl})
            kept += 1
            by_fam[fam] = by_fam.get(fam, 0) + 1

    with open(args.out, "w") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")
    print(f"\nSFT corpus: {kept} oracle-verified pairs ({rejected} rejected) "
          f"-> {args.out}")
    print("per family:", by_fam)
    print("Every completion is I/O-equivalence-verified correct (no bad training "
          "data). Next: SFT the base model on this, then GRPO on the V2 oracle.")


if __name__ == "__main__":
    main()
