#!/usr/bin/env python3
"""
gen_candidate_bitstream.py  -  Pack LLM CANDIDATES (not reference designs) into
batched bitstreams, for the simulation/silicon reward-gap study.

Every prior RL-for-RTL reward is simulation-based. This builds the instrument
to test whether that signal agrees with real silicon on actual LLM output:
take candidates from build_dataset's dataset.jsonl (each already has a
simulation reward), run them on the PYNQ-Z2, and later compare the hardware
reward to the simulation reward. Disagreements (predicted: reset/init
semantics, latches, races) are the contribution.

Reuses the exact dut_top + headless-Vivado structure of gen_bitstream.py.
Each candidate's module is renamed to a unique slot id (u{slot}_{design}) so
64 candidates -- including several for the same design -- share one bitstream
without name collisions. The DUT interface (ports/outwires/probe) comes from
the design's manifest record, identical to how the references were packed.

Only compile_ok candidates are eligible (a candidate that won't even compile
scores 0 in both sim and silicon -- no gap to measure; the interesting ones
compile and then behave differently). Selection is stratified across the
simulation-reward range, oversampling the mid band where sim/silicon
divergence is most likely.

Usage (run anywhere with the repo; emits to rtl/cand_batches/):
    python gen_candidate_bitstream.py --dataset fpga/dataset.jsonl --n 512
    python gen_candidate_bitstream.py --batch 64 --seed 0

Then on the laptop:
    for k in $(seq 0 7); do vivado -mode batch -source \
        rtl/cand_batches/build_cb$k.tcl; done
Then on the board:
    sudo python3 capture_waveforms.py --bit-dir rtl/cand_batches \
        --manifest rtl/cand_batches/cand_manifest.json --rtl-lib <ignored> \
        (use score_hw_candidates.py afterwards -- see that script)
"""

import os
import re
import json
import random
import argparse
import collections

from gen_bitstream import wire_names, rename   # proven helpers

ROOT = os.path.dirname(os.path.abspath(__file__))
RTL_LIB = os.path.join(ROOT, "rtl_library")
OUT_DIR = os.path.join(ROOT, "rtl", "cand_batches")
CAND_DIR = os.path.join(OUT_DIR, "cand")


def load_manifest():
    with open(os.path.join(RTL_LIB, "manifest.json")) as f:
        return {r["name"]: r for r in json.load(f)}


def rename_module(rtl, old, new):
    """Rename the module declaration `module <old>` -> `module <new>`.

    Only the first declaration is renamed; flat single-module candidates have
    no internal references to the top name, so this is safe.
    """
    return re.sub(r"\bmodule\s+" + re.escape(old) + r"\b",
                  "module " + new, rtl, count=1)


def select(records, manifest, n, seed):
    """Stratified pick of compile_ok candidates across the reward range.

    Bins favour the mid band (0.05-0.95): reset/init/latch divergences show up
    as partial simulation rewards, so that's where silicon is most likely to
    disagree. Saturated (==1.0) and dead (~0) candidates are included sparsely
    as controls.
    """
    rng = random.Random(seed)
    bins = collections.defaultdict(list)
    for rec in records:
        if not rec.get("compile_ok"):
            continue
        if rec["design"] not in manifest:
            continue
        r = rec["reward"]
        if r >= 0.999:
            b = "sat"
        elif r <= 0.05:
            b = "dead"
        elif r < 0.5:
            b = "lo"
        elif r < 0.9:
            b = "mid"
        else:
            b = "hi"
        bins[b].append(rec)
    # weights: concentrate on lo/mid/hi (the live band), thin controls
    quota = {"lo": 0.30, "mid": 0.30, "hi": 0.20, "sat": 0.10, "dead": 0.10}
    picked = []
    for b, frac in quota.items():
        pool = bins.get(b, [])
        rng.shuffle(pool)
        picked.extend(pool[:int(round(n * frac))])
    rng.shuffle(picked)
    return picked[:n]


def emit_batch(batch_id, slots):
    """slots: list of dicts {module, rec, sim_reward, design, cand_idx}."""
    sw = max(1, (len(slots) - 1).bit_length())
    decls, insts, cases = [], [], []
    for local_sel, s in enumerate(slots):
        rec = s["rec"]
        pfx = f"d{local_sel}_"
        mp = {nm: pfx + nm for nm in wire_names(rec["outwires"])}
        for decl in rec["outwires"]:
            decls.append("    " + rename(decl, mp))
        ports = re.sub(r"(\.\w+\s*\()([^)]*)(\))",
                       lambda m: m.group(1) + rename(m.group(2), mp) + m.group(3),
                       rec["ports"])
        insts.append(
            f"    {s['module']} u_{pfx[:-1]} "
            f"( .clk(clk), .rst_n(rst_n), {ports} );")
        cases.append(f"            {sw}'d{local_sel}: probe = "
                     f"{rename(rec['probe'], mp)};")

    body = f"""`timescale 1ns/1ps
// Auto-generated by gen_candidate_bitstream.py - candidate batch {batch_id}.
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [{sw-1}:0] sel,
    output reg  [15:0] probe
);
    reg [31:0] cnt;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) cnt <= 32'b0;
        else        cnt <= cnt + 1'b1;

{chr(10).join(decls)}

{chr(10).join(insts)}

    always @(*) begin
        case (sel)
{chr(10).join(cases)}
            default: probe = 16'b0;
        endcase
    end
endmodule
"""
    with open(os.path.join(OUT_DIR, f"dut_top_cb{batch_id}.v"), "w") as f:
        f.write(body)

    cand_files = " \\\n    ".join(
        f"[file join $ROOT rtl cand_batches cand {s['module']}.v]"
        for s in slots)
    tcl = f"""# Auto-generated - candidate batch {batch_id} (self-contained).
set BATCH   {batch_id}
set PART    "xc7z020clg400-1"
set CLK_MHZ 100
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set OUT     [file join $ROOT rtl cand_batches out_cb{batch_id}]
file mkdir $OUT

create_project sys_cb{batch_id} [file join $OUT proj] -part $PART -force
add_files [list \\
    [file join $ROOT rtl la_axi_wide.v] \\
    [file join $ROOT rtl cand_batches dut_top_cb{batch_id}.v] \\
    {cand_files} ]
update_compile_order -fileset sources_1
# Read candidates as SystemVerilog, matching how they were sim-validated
# (iverilog -g2012) and synth_check.tcl. Verilog-2001 mode is stricter and
# would reject valid-under-SV constructs (e.g. logic driven by assign),
# injecting language-mode artifacts into the gap study.
set_property file_type SystemVerilog \\
    [get_files -filter {{NAME =~ "*cand_batches/cand/*"}}]

create_bd_design "system"
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {{make_external "FIXED_IO, DDR" apply_board_preset "1"}} \\
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \\
    [get_bd_cells ps7]
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \\
    -config {{Master "/ps7/M_AXI_GP0" Clk "Auto"}} \\
    [get_bd_intf_pins la0/S_AXI]
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]
assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \\
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \\
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \\
    [file join $OUT system_cb{batch_id}.bit]
set hwh [glob -nocomplain \\
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \\
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {{$hwh ne ""}} {{
    file copy -force [lindex $hwh 0] [file join $OUT system_cb{batch_id}.hwh]
}}
puts "CAND BATCH {batch_id} DONE"
"""
    with open(os.path.join(OUT_DIR, f"build_cb{batch_id}.tcl"), "w") as f:
        f.write(tcl)
    return sw


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", default=os.path.join(ROOT, "dataset.jsonl"))
    ap.add_argument("--n", type=int, default=512,
                    help="candidates to pack (across all batches)")
    ap.add_argument("--batch", type=int, default=64)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--exclude", default=None,
                    help="file of module names to skip (e.g. ppa.jsonl.fails "
                         "from run_ppa); use the same --seed to reproduce the "
                         "selection")
    args = ap.parse_args()

    manifest = load_manifest()
    records = []
    per_design_idx = collections.Counter()
    with open(args.dataset) as f:
        for line in f:
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            rec["_idx"] = per_design_idx[rec["design"]]
            per_design_idx[rec["design"]] += 1
            records.append(rec)

    picked = select(records, manifest, args.n, args.seed)
    os.makedirs(CAND_DIR, exist_ok=True)

    exclude = set()
    if args.exclude and os.path.exists(args.exclude):
        exclude = {ln.strip() for ln in open(args.exclude) if ln.strip()}
        print(f"excluding {len(exclude)} modules from {args.exclude}")

    slots = []
    for rec in picked:
        design = rec["design"]
        # identity-based name (design + per-design candidate index): stable
        # across re-runs, so a run_ppa .fails list stays valid under --exclude.
        module = f"c{rec['_idx']}_{design}"
        if module in exclude:
            continue
        rtl = rename_module(rec["rtl"], design, module)
        with open(os.path.join(CAND_DIR, module + ".v"), "w") as f:
            f.write(rtl)
        srec = dict(manifest[design])
        srec["name"] = module
        slots.append({"module": module, "rec": srec, "design": design,
                      "sim_reward": rec["reward"], "cand_idx": rec["_idx"]})

    batches = [slots[i:i + args.batch]
               for i in range(0, len(slots), args.batch)]
    global_map = []
    for k, bslots in enumerate(batches):
        emit_batch(k, bslots)
        for local_sel, s in enumerate(bslots):
            d = manifest[s["design"]]
            global_map.append({
                "batch": k, "local_sel": local_sel,
                "module": s["module"], "design": s["design"],
                "cand_idx": s["cand_idx"], "sim_reward": s["sim_reward"],
                "probe_mask": d["probe_mask"], "period": d["period"],
                "family": d["family"],
            })
        print(f"cand batch {k:2d}: {len(bslots):3d} candidates")

    with open(os.path.join(OUT_DIR, "cand_manifest.json"), "w") as f:
        json.dump({"batch_size": args.batch, "n_batches": len(batches),
                   "designs": global_map}, f, indent=1)
    print(f"\n{len(slots)} candidates -> {len(batches)} bitstreams "
          f"(batch {args.batch}). Wrote to {OUT_DIR}")
    print("Next: build the cb*.tcl on the laptop, capture on the board, then "
          "score_hw_candidates.py to compute the sim/silicon reward gap.")


if __name__ == "__main__":
    main()
