
####################################################################################
# Generated by Vivado 2026.1 built on 'Tue Jun 16 11:02:23 MDT 2026' by 'xbuild'
# Command Used: write_xdc C:/Users/Amine/mas/fpga-repo/timing_path_audit_v1/replay_20260905_02/reports/constraints.xdc
####################################################################################


# User Generated XDC timing constraints 

create_clock -period 5.000 -name vclk [get_ports clk]
set_input_delay -clock vclk 0.000 [get_ports [list rst_n {x[0]} {x[1]} {x[2]} {x[3]} {x[4]} {x[5]} {x[6]} {x[7]}]]
set_output_delay -clock vclk 0.000 [get_ports -quiet -filter {DIRECTION == OUT}]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
