`timescale 1ns/1ps
// Generated by gen_study2_board.py; selection rules are frozen separately.
module dut_top (
    input wire clk, input wire rst_n, input wire cap, input wire [5:0] sel,
    output reg [15:0] probe
);
    wire dut_rst_n = rst_n & cap;
    reg [31:0] cnt;
    always @(posedge clk)
        if (!rst_n || !cap) cnt <= 32'b0;
        else cnt <= cnt + 1'b1;
    wire [15:0] y0;
    wire [15:0] y1;
    wire [15:0] y2;
    wire [15:0] y3;
    wire [15:0] y4;
    wire [15:0] y5;
    wire [15:0] y6;
    wire [15:0] y7;
    wire [15:0] y8;
    wire [15:0] y9;
    wire [15:0] y10;
    sft__fir34_v1_8b__g0 u0 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y0));
    rf_s2__fir34_v1_8b__g0 u1 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y1));
    sft__firr20_v6__g0 u2 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y2));
    rf_s2__firr20_v6__g0 u3 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y3));
    sft__poly16_v13_8b__g0 u4 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y4));
    rf_s2__poly16_v13_8b__g0 u5 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y5));
    sft__iir18_v7__g0 u6 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y6));
    rf_s1__iir18_v7__g1 u7 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y7));
    sft__med19__g0 u8 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y8));
    rf_s2__med19__g6 u9 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y9));
    echo8b u10 (.clk(clk), .rst_n(dut_rst_n), .x(cnt[7:0]), .y(y10));
    always @(*) begin
        case (sel)
            6'd0: probe = y0;
            6'd1: probe = y1;
            6'd2: probe = y2;
            6'd3: probe = y3;
            6'd4: probe = y4;
            6'd5: probe = y5;
            6'd6: probe = y6;
            6'd7: probe = y7;
            6'd8: probe = y8;
            6'd9: probe = y9;
            6'd10: probe = y10;
            default: probe = 16'b0;
        endcase
    end
endmodule
