# Auto-generated by gen_bitstream.py  -  batch 6 (self-contained).
# Build:  vivado -mode batch -source build_b6.tcl
set BATCH   6
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b6]
file mkdir $OUT

create_project sys_b6 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b6.v] \
    [file join $RTL_LIB johnson7 design.v] \
    [file join $RTL_LIB ring8 design.v] \
    [file join $RTL_LIB johnson8 design.v] \
    [file join $RTL_LIB ring9 design.v] \
    [file join $RTL_LIB johnson9 design.v] \
    [file join $RTL_LIB ring10 design.v] \
    [file join $RTL_LIB johnson10 design.v] \
    [file join $RTL_LIB ring12 design.v] \
    [file join $RTL_LIB johnson12 design.v] \
    [file join $RTL_LIB ring16 design.v] \
    [file join $RTL_LIB johnson16 design.v] \
    [file join $RTL_LIB tccnt4_15 design.v] \
    [file join $RTL_LIB tccnt4_8 design.v] \
    [file join $RTL_LIB tccnt4_5 design.v] \
    [file join $RTL_LIB tccnt4_4 design.v] \
    [file join $RTL_LIB tccnt4_12 design.v] \
    [file join $RTL_LIB tccnt5_31 design.v] \
    [file join $RTL_LIB tccnt5_16 design.v] \
    [file join $RTL_LIB tccnt5_10 design.v] \
    [file join $RTL_LIB tccnt5_8 design.v] \
    [file join $RTL_LIB tccnt5_24 design.v] \
    [file join $RTL_LIB tccnt6_63 design.v] \
    [file join $RTL_LIB tccnt6_32 design.v] \
    [file join $RTL_LIB tccnt6_21 design.v] \
    [file join $RTL_LIB tccnt6_16 design.v] \
    [file join $RTL_LIB tccnt6_48 design.v] \
    [file join $RTL_LIB tccnt7_127 design.v] \
    [file join $RTL_LIB tccnt7_64 design.v] \
    [file join $RTL_LIB tccnt7_42 design.v] \
    [file join $RTL_LIB tccnt7_32 design.v] \
    [file join $RTL_LIB tccnt7_96 design.v] \
    [file join $RTL_LIB tccnt8_255 design.v] \
    [file join $RTL_LIB tccnt8_128 design.v] \
    [file join $RTL_LIB tccnt8_85 design.v] \
    [file join $RTL_LIB tccnt8_64 design.v] \
    [file join $RTL_LIB tccnt8_192 design.v] \
    [file join $RTL_LIB sipo_l3b design.v] \
    [file join $RTL_LIB sipo_r3b design.v] \
    [file join $RTL_LIB sipo_l4b design.v] \
    [file join $RTL_LIB sipo_r4b design.v] \
    [file join $RTL_LIB sipo_l5b design.v] \
    [file join $RTL_LIB sipo_r5b design.v] \
    [file join $RTL_LIB sipo_l6b design.v] \
    [file join $RTL_LIB sipo_r6b design.v] \
    [file join $RTL_LIB sipo_l7b design.v] \
    [file join $RTL_LIB sipo_r7b design.v] \
    [file join $RTL_LIB sipo_l8b design.v] \
    [file join $RTL_LIB sipo_r8b design.v] \
    [file join $RTL_LIB sipo_l9b design.v] \
    [file join $RTL_LIB sipo_r9b design.v] \
    [file join $RTL_LIB sipo_l10b design.v] \
    [file join $RTL_LIB sipo_r10b design.v] \
    [file join $RTL_LIB sipo_l11b design.v] \
    [file join $RTL_LIB sipo_r11b design.v] \
    [file join $RTL_LIB sipo_l12b design.v] \
    [file join $RTL_LIB sipo_r12b design.v] \
    [file join $RTL_LIB sipo_l13b design.v] \
    [file join $RTL_LIB sipo_r13b design.v] \
    [file join $RTL_LIB sipo_l14b design.v] \
    [file join $RTL_LIB sipo_r14b design.v] \
    [file join $RTL_LIB sipo_l15b design.v] \
    [file join $RTL_LIB sipo_r15b design.v] \
    [file join $RTL_LIB sipo_l16b design.v] \
    [file join $RTL_LIB sipo_r16b design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b6.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b6.hwh]
}
puts "BATCH 6 DONE -> [file join $OUT system_b6.bit]"
