# Auto-generated by gen_bitstream.py  -  batch 13 (self-contained).
# Build:  vivado -mode batch -source build_b13.tcl
set BATCH   13
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b13]
file mkdir $OUT

create_project sys_b13 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b13.v] \
    [file join $RTL_LIB prienc16 design.v] \
    [file join $RTL_LIB decoder2to4 design.v] \
    [file join $RTL_LIB decoder3to8 design.v] \
    [file join $RTL_LIB decoder4to16 design.v] \
    [file join $RTL_LIB mux2x1b design.v] \
    [file join $RTL_LIB mux2x2b design.v] \
    [file join $RTL_LIB mux2x3b design.v] \
    [file join $RTL_LIB mux2x4b design.v] \
    [file join $RTL_LIB mux4x1b design.v] \
    [file join $RTL_LIB mux4x2b design.v] \
    [file join $RTL_LIB mux4x3b design.v] \
    [file join $RTL_LIB mux4x4b design.v] \
    [file join $RTL_LIB mux8x1b design.v] \
    [file join $RTL_LIB mux8x2b design.v] \
    [file join $RTL_LIB mux8x3b design.v] \
    [file join $RTL_LIB mux16x1b design.v] \
    [file join $RTL_LIB demux1to2 design.v] \
    [file join $RTL_LIB demux1to4 design.v] \
    [file join $RTL_LIB demux1to8 design.v] \
    [file join $RTL_LIB demux1to16 design.v] \
    [file join $RTL_LIB gray2bin3 design.v] \
    [file join $RTL_LIB gray2bin4 design.v] \
    [file join $RTL_LIB gray2bin5 design.v] \
    [file join $RTL_LIB gray2bin6 design.v] \
    [file join $RTL_LIB gray2bin7 design.v] \
    [file join $RTL_LIB gray2bin8 design.v] \
    [file join $RTL_LIB gray2bin9 design.v] \
    [file join $RTL_LIB gray2bin10 design.v] \
    [file join $RTL_LIB gray2bin11 design.v] \
    [file join $RTL_LIB gray2bin12 design.v] \
    [file join $RTL_LIB gray2bin13 design.v] \
    [file join $RTL_LIB gray2bin14 design.v] \
    [file join $RTL_LIB gray2bin15 design.v] \
    [file join $RTL_LIB gray2bin16 design.v] \
    [file join $RTL_LIB alu4_2op design.v] \
    [file join $RTL_LIB alu4_3op design.v] \
    [file join $RTL_LIB alu4_4op design.v] \
    [file join $RTL_LIB alu4_5op design.v] \
    [file join $RTL_LIB alu4_6op design.v] \
    [file join $RTL_LIB alu4_7op design.v] \
    [file join $RTL_LIB alu4_8op design.v] \
    [file join $RTL_LIB alu5_2op design.v] \
    [file join $RTL_LIB alu5_3op design.v] \
    [file join $RTL_LIB alu5_4op design.v] \
    [file join $RTL_LIB alu5_5op design.v] \
    [file join $RTL_LIB alu5_6op design.v] \
    [file join $RTL_LIB alu5_7op design.v] \
    [file join $RTL_LIB alu5_8op design.v] \
    [file join $RTL_LIB alu6_2op design.v] \
    [file join $RTL_LIB alu6_3op design.v] \
    [file join $RTL_LIB alu6_4op design.v] \
    [file join $RTL_LIB alu6_5op design.v] \
    [file join $RTL_LIB alu6_6op design.v] \
    [file join $RTL_LIB alu6_7op design.v] \
    [file join $RTL_LIB alu6_8op design.v] \
    [file join $RTL_LIB alu7_2op design.v] \
    [file join $RTL_LIB alu7_3op design.v] \
    [file join $RTL_LIB alu7_4op design.v] \
    [file join $RTL_LIB alu7_5op design.v] \
    [file join $RTL_LIB alu7_6op design.v] \
    [file join $RTL_LIB alu7_7op design.v] \
    [file join $RTL_LIB alu7_8op design.v] \
    [file join $RTL_LIB alu8_2op design.v] \
    [file join $RTL_LIB alu8_3op design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b13.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b13.hwh]
}
puts "BATCH 13 DONE -> [file join $OUT system_b13.bit]"
