# Auto-generated by gen_bitstream.py  -  batch 1 (self-contained).
# Build:  vivado -mode batch -source build_b1.tcl
set BATCH   1
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b1]
file mkdir $OUT

create_project sys_b1 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b1.v] \
    [file join $RTL_LIB mod42_counter design.v] \
    [file join $RTL_LIB mod43_counter design.v] \
    [file join $RTL_LIB mod44_counter design.v] \
    [file join $RTL_LIB mod45_counter design.v] \
    [file join $RTL_LIB mod46_counter design.v] \
    [file join $RTL_LIB mod47_counter design.v] \
    [file join $RTL_LIB mod48_counter design.v] \
    [file join $RTL_LIB mod49_counter design.v] \
    [file join $RTL_LIB mod50_counter design.v] \
    [file join $RTL_LIB mod51_counter design.v] \
    [file join $RTL_LIB mod52_counter design.v] \
    [file join $RTL_LIB mod53_counter design.v] \
    [file join $RTL_LIB mod54_counter design.v] \
    [file join $RTL_LIB mod55_counter design.v] \
    [file join $RTL_LIB mod56_counter design.v] \
    [file join $RTL_LIB mod57_counter design.v] \
    [file join $RTL_LIB mod58_counter design.v] \
    [file join $RTL_LIB mod59_counter design.v] \
    [file join $RTL_LIB mod60_counter design.v] \
    [file join $RTL_LIB mod61_counter design.v] \
    [file join $RTL_LIB mod62_counter design.v] \
    [file join $RTL_LIB mod63_counter design.v] \
    [file join $RTL_LIB mod64_counter design.v] \
    [file join $RTL_LIB mod65_counter design.v] \
    [file join $RTL_LIB mod66_counter design.v] \
    [file join $RTL_LIB mod67_counter design.v] \
    [file join $RTL_LIB mod68_counter design.v] \
    [file join $RTL_LIB mod69_counter design.v] \
    [file join $RTL_LIB mod70_counter design.v] \
    [file join $RTL_LIB mod71_counter design.v] \
    [file join $RTL_LIB mod72_counter design.v] \
    [file join $RTL_LIB mod73_counter design.v] \
    [file join $RTL_LIB mod74_counter design.v] \
    [file join $RTL_LIB mod75_counter design.v] \
    [file join $RTL_LIB mod76_counter design.v] \
    [file join $RTL_LIB mod77_counter design.v] \
    [file join $RTL_LIB mod78_counter design.v] \
    [file join $RTL_LIB mod79_counter design.v] \
    [file join $RTL_LIB mod80_counter design.v] \
    [file join $RTL_LIB mod81_counter design.v] \
    [file join $RTL_LIB mod82_counter design.v] \
    [file join $RTL_LIB mod83_counter design.v] \
    [file join $RTL_LIB mod84_counter design.v] \
    [file join $RTL_LIB mod85_counter design.v] \
    [file join $RTL_LIB mod86_counter design.v] \
    [file join $RTL_LIB mod87_counter design.v] \
    [file join $RTL_LIB mod88_counter design.v] \
    [file join $RTL_LIB mod89_counter design.v] \
    [file join $RTL_LIB mod90_counter design.v] \
    [file join $RTL_LIB mod91_counter design.v] \
    [file join $RTL_LIB mod92_counter design.v] \
    [file join $RTL_LIB mod93_counter design.v] \
    [file join $RTL_LIB mod94_counter design.v] \
    [file join $RTL_LIB mod95_counter design.v] \
    [file join $RTL_LIB mod96_counter design.v] \
    [file join $RTL_LIB mod98_counter design.v] \
    [file join $RTL_LIB mod100_counter design.v] \
    [file join $RTL_LIB mod102_counter design.v] \
    [file join $RTL_LIB mod104_counter design.v] \
    [file join $RTL_LIB mod106_counter design.v] \
    [file join $RTL_LIB mod108_counter design.v] \
    [file join $RTL_LIB mod110_counter design.v] \
    [file join $RTL_LIB mod112_counter design.v] \
    [file join $RTL_LIB mod114_counter design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b1.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b1.hwh]
}
puts "BATCH 1 DONE -> [file join $OUT system_b1.bit]"
