# Auto-generated by gen_bitstream.py  -  batch 8 (self-contained).
# Build:  vivado -mode batch -source build_b8.tcl
set BATCH   8
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b8]
file mkdir $OUT

create_project sys_b8 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b8.v] \
    [file join $RTL_LIB sub5b design.v] \
    [file join $RTL_LIB addsub5b design.v] \
    [file join $RTL_LIB add6b design.v] \
    [file join $RTL_LIB sub6b design.v] \
    [file join $RTL_LIB addsub6b design.v] \
    [file join $RTL_LIB add7b design.v] \
    [file join $RTL_LIB sub7b design.v] \
    [file join $RTL_LIB addsub7b design.v] \
    [file join $RTL_LIB add8b design.v] \
    [file join $RTL_LIB sub8b design.v] \
    [file join $RTL_LIB addsub8b design.v] \
    [file join $RTL_LIB add9b design.v] \
    [file join $RTL_LIB sub9b design.v] \
    [file join $RTL_LIB addsub9b design.v] \
    [file join $RTL_LIB add10b design.v] \
    [file join $RTL_LIB sub10b design.v] \
    [file join $RTL_LIB addsub10b design.v] \
    [file join $RTL_LIB add11b design.v] \
    [file join $RTL_LIB sub11b design.v] \
    [file join $RTL_LIB addsub11b design.v] \
    [file join $RTL_LIB add12b design.v] \
    [file join $RTL_LIB sub12b design.v] \
    [file join $RTL_LIB addsub12b design.v] \
    [file join $RTL_LIB add13b design.v] \
    [file join $RTL_LIB sub13b design.v] \
    [file join $RTL_LIB addsub13b design.v] \
    [file join $RTL_LIB add14b design.v] \
    [file join $RTL_LIB sub14b design.v] \
    [file join $RTL_LIB addsub14b design.v] \
    [file join $RTL_LIB add15b design.v] \
    [file join $RTL_LIB sub15b design.v] \
    [file join $RTL_LIB addsub15b design.v] \
    [file join $RTL_LIB satadd3b design.v] \
    [file join $RTL_LIB satadd4b design.v] \
    [file join $RTL_LIB satadd5b design.v] \
    [file join $RTL_LIB satadd6b design.v] \
    [file join $RTL_LIB satadd7b design.v] \
    [file join $RTL_LIB satadd8b design.v] \
    [file join $RTL_LIB satadd9b design.v] \
    [file join $RTL_LIB satadd10b design.v] \
    [file join $RTL_LIB satadd11b design.v] \
    [file join $RTL_LIB satadd12b design.v] \
    [file join $RTL_LIB satadd13b design.v] \
    [file join $RTL_LIB satadd14b design.v] \
    [file join $RTL_LIB satadd15b design.v] \
    [file join $RTL_LIB logical_lsh4 design.v] \
    [file join $RTL_LIB rotate_lsh4 design.v] \
    [file join $RTL_LIB logical_rsh4 design.v] \
    [file join $RTL_LIB rotate_rsh4 design.v] \
    [file join $RTL_LIB logical_lsh5 design.v] \
    [file join $RTL_LIB logical_rsh5 design.v] \
    [file join $RTL_LIB logical_lsh6 design.v] \
    [file join $RTL_LIB logical_rsh6 design.v] \
    [file join $RTL_LIB logical_lsh7 design.v] \
    [file join $RTL_LIB logical_rsh7 design.v] \
    [file join $RTL_LIB logical_lsh8 design.v] \
    [file join $RTL_LIB rotate_lsh8 design.v] \
    [file join $RTL_LIB logical_rsh8 design.v] \
    [file join $RTL_LIB rotate_rsh8 design.v] \
    [file join $RTL_LIB logical_lsh10 design.v] \
    [file join $RTL_LIB logical_rsh10 design.v] \
    [file join $RTL_LIB logical_lsh12 design.v] \
    [file join $RTL_LIB logical_rsh12 design.v] \
    [file join $RTL_LIB logical_lsh16 design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b8.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b8.hwh]
}
puts "BATCH 8 DONE -> [file join $OUT system_b8.bit]"
