# Auto-generated by gen_bitstream.py  -  batch 9 (self-contained).
# Build:  vivado -mode batch -source build_b9.tcl
set BATCH   9
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b9]
file mkdir $OUT

create_project sys_b9 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b9.v] \
    [file join $RTL_LIB rotate_lsh16 design.v] \
    [file join $RTL_LIB logical_rsh16 design.v] \
    [file join $RTL_LIB rotate_rsh16 design.v] \
    [file join $RTL_LIB rotl4_1 design.v] \
    [file join $RTL_LIB rotl4_2 design.v] \
    [file join $RTL_LIB rotl4_3 design.v] \
    [file join $RTL_LIB rotl6_1 design.v] \
    [file join $RTL_LIB rotl6_2 design.v] \
    [file join $RTL_LIB rotl6_3 design.v] \
    [file join $RTL_LIB rotl6_5 design.v] \
    [file join $RTL_LIB rotl8_1 design.v] \
    [file join $RTL_LIB rotl8_2 design.v] \
    [file join $RTL_LIB rotl8_3 design.v] \
    [file join $RTL_LIB rotl8_4 design.v] \
    [file join $RTL_LIB rotl8_7 design.v] \
    [file join $RTL_LIB rotl10_1 design.v] \
    [file join $RTL_LIB rotl10_2 design.v] \
    [file join $RTL_LIB rotl10_3 design.v] \
    [file join $RTL_LIB rotl10_5 design.v] \
    [file join $RTL_LIB rotl10_9 design.v] \
    [file join $RTL_LIB rotl12_1 design.v] \
    [file join $RTL_LIB rotl12_2 design.v] \
    [file join $RTL_LIB rotl12_3 design.v] \
    [file join $RTL_LIB rotl12_6 design.v] \
    [file join $RTL_LIB rotl12_11 design.v] \
    [file join $RTL_LIB rotl16_1 design.v] \
    [file join $RTL_LIB rotl16_2 design.v] \
    [file join $RTL_LIB rotl16_3 design.v] \
    [file join $RTL_LIB rotl16_4 design.v] \
    [file join $RTL_LIB rotl16_8 design.v] \
    [file join $RTL_LIB rotl16_15 design.v] \
    [file join $RTL_LIB cmp2b design.v] \
    [file join $RTL_LIB cmp3b design.v] \
    [file join $RTL_LIB cmp4b design.v] \
    [file join $RTL_LIB cmp5b design.v] \
    [file join $RTL_LIB cmp6b design.v] \
    [file join $RTL_LIB cmp7b design.v] \
    [file join $RTL_LIB cmp8b design.v] \
    [file join $RTL_LIB cmp9b design.v] \
    [file join $RTL_LIB cmp10b design.v] \
    [file join $RTL_LIB cmp11b design.v] \
    [file join $RTL_LIB cmp12b design.v] \
    [file join $RTL_LIB cmp13b design.v] \
    [file join $RTL_LIB cmp14b design.v] \
    [file join $RTL_LIB cmp15b design.v] \
    [file join $RTL_LIB cmp16b design.v] \
    [file join $RTL_LIB min2b design.v] \
    [file join $RTL_LIB max2b design.v] \
    [file join $RTL_LIB min3b design.v] \
    [file join $RTL_LIB max3b design.v] \
    [file join $RTL_LIB min4b design.v] \
    [file join $RTL_LIB max4b design.v] \
    [file join $RTL_LIB min5b design.v] \
    [file join $RTL_LIB max5b design.v] \
    [file join $RTL_LIB min6b design.v] \
    [file join $RTL_LIB max6b design.v] \
    [file join $RTL_LIB min7b design.v] \
    [file join $RTL_LIB max7b design.v] \
    [file join $RTL_LIB min8b design.v] \
    [file join $RTL_LIB max8b design.v] \
    [file join $RTL_LIB min9b design.v] \
    [file join $RTL_LIB max9b design.v] \
    [file join $RTL_LIB min10b design.v] \
    [file join $RTL_LIB max10b design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b9.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b9.hwh]
}
puts "BATCH 9 DONE -> [file join $OUT system_b9.bit]"
