# Auto-generated by gen_bitstream.py  -  batch 10 (self-contained).
# Build:  vivado -mode batch -source build_b10.tcl
set BATCH   10
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b10]
file mkdir $OUT

create_project sys_b10 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b10.v] \
    [file join $RTL_LIB min11b design.v] \
    [file join $RTL_LIB max11b design.v] \
    [file join $RTL_LIB min12b design.v] \
    [file join $RTL_LIB max12b design.v] \
    [file join $RTL_LIB min13b design.v] \
    [file join $RTL_LIB max13b design.v] \
    [file join $RTL_LIB min14b design.v] \
    [file join $RTL_LIB max14b design.v] \
    [file join $RTL_LIB min15b design.v] \
    [file join $RTL_LIB max15b design.v] \
    [file join $RTL_LIB min16b design.v] \
    [file join $RTL_LIB max16b design.v] \
    [file join $RTL_LIB window4_4_12 design.v] \
    [file join $RTL_LIB window4_1_8 design.v] \
    [file join $RTL_LIB window4_5_10 design.v] \
    [file join $RTL_LIB window4_2_8 design.v] \
    [file join $RTL_LIB window4_4_15 design.v] \
    [file join $RTL_LIB window5_8_24 design.v] \
    [file join $RTL_LIB window5_1_16 design.v] \
    [file join $RTL_LIB window5_10_21 design.v] \
    [file join $RTL_LIB window5_4_16 design.v] \
    [file join $RTL_LIB window5_8_31 design.v] \
    [file join $RTL_LIB window6_16_48 design.v] \
    [file join $RTL_LIB window6_1_32 design.v] \
    [file join $RTL_LIB window6_21_42 design.v] \
    [file join $RTL_LIB window6_8_32 design.v] \
    [file join $RTL_LIB window6_16_63 design.v] \
    [file join $RTL_LIB window7_32_96 design.v] \
    [file join $RTL_LIB window7_1_64 design.v] \
    [file join $RTL_LIB window7_42_85 design.v] \
    [file join $RTL_LIB window7_16_64 design.v] \
    [file join $RTL_LIB window7_32_127 design.v] \
    [file join $RTL_LIB window8_64_192 design.v] \
    [file join $RTL_LIB window8_1_128 design.v] \
    [file join $RTL_LIB window8_85_170 design.v] \
    [file join $RTL_LIB window8_32_128 design.v] \
    [file join $RTL_LIB window8_64_255 design.v] \
    [file join $RTL_LIB clamp4_12 design.v] \
    [file join $RTL_LIB clamp4_9 design.v] \
    [file join $RTL_LIB clamp4_8 design.v] \
    [file join $RTL_LIB clamp4_14 design.v] \
    [file join $RTL_LIB clamp5_24 design.v] \
    [file join $RTL_LIB clamp5_17 design.v] \
    [file join $RTL_LIB clamp5_16 design.v] \
    [file join $RTL_LIB clamp5_30 design.v] \
    [file join $RTL_LIB clamp6_48 design.v] \
    [file join $RTL_LIB clamp6_33 design.v] \
    [file join $RTL_LIB clamp6_32 design.v] \
    [file join $RTL_LIB clamp6_62 design.v] \
    [file join $RTL_LIB clamp7_96 design.v] \
    [file join $RTL_LIB clamp7_65 design.v] \
    [file join $RTL_LIB clamp7_64 design.v] \
    [file join $RTL_LIB clamp7_126 design.v] \
    [file join $RTL_LIB clamp8_192 design.v] \
    [file join $RTL_LIB clamp8_129 design.v] \
    [file join $RTL_LIB clamp8_128 design.v] \
    [file join $RTL_LIB clamp8_254 design.v] \
    [file join $RTL_LIB thresh4_8 design.v] \
    [file join $RTL_LIB thresh4_12 design.v] \
    [file join $RTL_LIB thresh4_4 design.v] \
    [file join $RTL_LIB thresh4_14 design.v] \
    [file join $RTL_LIB thresh5_16 design.v] \
    [file join $RTL_LIB thresh5_24 design.v] \
    [file join $RTL_LIB thresh5_8 design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b10.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b10.hwh]
}
puts "BATCH 10 DONE -> [file join $OUT system_b10.bit]"
