# Auto-generated by gen_bitstream.py  -  batch 7 (self-contained).
# Build:  vivado -mode batch -source build_b7.tcl
set BATCH   7
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b7]
file mkdir $OUT

create_project sys_b7 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b7.v] \
    [file join $RTL_LIB mul2x2 design.v] \
    [file join $RTL_LIB mul2x3 design.v] \
    [file join $RTL_LIB mul2x4 design.v] \
    [file join $RTL_LIB mul2x5 design.v] \
    [file join $RTL_LIB mul2x6 design.v] \
    [file join $RTL_LIB mul2x7 design.v] \
    [file join $RTL_LIB mul2x8 design.v] \
    [file join $RTL_LIB mul3x2 design.v] \
    [file join $RTL_LIB mul3x3 design.v] \
    [file join $RTL_LIB mul3x4 design.v] \
    [file join $RTL_LIB mul3x5 design.v] \
    [file join $RTL_LIB mul3x6 design.v] \
    [file join $RTL_LIB mul3x7 design.v] \
    [file join $RTL_LIB mul3x8 design.v] \
    [file join $RTL_LIB mul4x2 design.v] \
    [file join $RTL_LIB mul4x3 design.v] \
    [file join $RTL_LIB mul4x4 design.v] \
    [file join $RTL_LIB mul4x5 design.v] \
    [file join $RTL_LIB mul4x6 design.v] \
    [file join $RTL_LIB mul4x7 design.v] \
    [file join $RTL_LIB mul4x8 design.v] \
    [file join $RTL_LIB mul5x2 design.v] \
    [file join $RTL_LIB mul5x3 design.v] \
    [file join $RTL_LIB mul5x4 design.v] \
    [file join $RTL_LIB mul5x5 design.v] \
    [file join $RTL_LIB mul5x6 design.v] \
    [file join $RTL_LIB mul5x7 design.v] \
    [file join $RTL_LIB mul5x8 design.v] \
    [file join $RTL_LIB mul6x2 design.v] \
    [file join $RTL_LIB mul6x3 design.v] \
    [file join $RTL_LIB mul6x4 design.v] \
    [file join $RTL_LIB mul6x5 design.v] \
    [file join $RTL_LIB mul6x6 design.v] \
    [file join $RTL_LIB mul6x7 design.v] \
    [file join $RTL_LIB mul6x8 design.v] \
    [file join $RTL_LIB mul7x2 design.v] \
    [file join $RTL_LIB mul7x3 design.v] \
    [file join $RTL_LIB mul7x4 design.v] \
    [file join $RTL_LIB mul7x5 design.v] \
    [file join $RTL_LIB mul7x6 design.v] \
    [file join $RTL_LIB mul7x7 design.v] \
    [file join $RTL_LIB mul7x8 design.v] \
    [file join $RTL_LIB mul8x2 design.v] \
    [file join $RTL_LIB mul8x3 design.v] \
    [file join $RTL_LIB mul8x4 design.v] \
    [file join $RTL_LIB mul8x5 design.v] \
    [file join $RTL_LIB mul8x6 design.v] \
    [file join $RTL_LIB mul8x7 design.v] \
    [file join $RTL_LIB smul2x2 design.v] \
    [file join $RTL_LIB smul3x3 design.v] \
    [file join $RTL_LIB smul4x4 design.v] \
    [file join $RTL_LIB smul5x5 design.v] \
    [file join $RTL_LIB smul6x6 design.v] \
    [file join $RTL_LIB smul7x7 design.v] \
    [file join $RTL_LIB add2b design.v] \
    [file join $RTL_LIB sub2b design.v] \
    [file join $RTL_LIB addsub2b design.v] \
    [file join $RTL_LIB add3b design.v] \
    [file join $RTL_LIB sub3b design.v] \
    [file join $RTL_LIB addsub3b design.v] \
    [file join $RTL_LIB add4b design.v] \
    [file join $RTL_LIB sub4b design.v] \
    [file join $RTL_LIB addsub4b design.v] \
    [file join $RTL_LIB add5b design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b7.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b7.hwh]
}
puts "BATCH 7 DONE -> [file join $OUT system_b7.bit]"
