# Auto-generated by gen_bitstream.py  -  batch 14 (self-contained).
# Build:  vivado -mode batch -source build_b14.tcl
set BATCH   14
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b14]
file mkdir $OUT

create_project sys_b14 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b14.v] \
    [file join $RTL_LIB alu8_4op design.v] \
    [file join $RTL_LIB alu8_5op design.v] \
    [file join $RTL_LIB alu8_6op design.v] \
    [file join $RTL_LIB alu8_7op design.v] \
    [file join $RTL_LIB alu8_8op design.v] \
    [file join $RTL_LIB alu10_2op design.v] \
    [file join $RTL_LIB alu10_3op design.v] \
    [file join $RTL_LIB alu10_4op design.v] \
    [file join $RTL_LIB alu10_5op design.v] \
    [file join $RTL_LIB alu10_6op design.v] \
    [file join $RTL_LIB alu10_7op design.v] \
    [file join $RTL_LIB alu10_8op design.v] \
    [file join $RTL_LIB alu12_2op design.v] \
    [file join $RTL_LIB alu12_3op design.v] \
    [file join $RTL_LIB alu12_4op design.v] \
    [file join $RTL_LIB alu12_5op design.v] \
    [file join $RTL_LIB alu12_6op design.v] \
    [file join $RTL_LIB alu12_7op design.v] \
    [file join $RTL_LIB alu12_8op design.v] \
    [file join $RTL_LIB lfsr4_0 design.v] \
    [file join $RTL_LIB lfsr5_1 design.v] \
    [file join $RTL_LIB lfsr6_2 design.v] \
    [file join $RTL_LIB lfsr7_3 design.v] \
    [file join $RTL_LIB lfsr8_4 design.v] \
    [file join $RTL_LIB lfsr8_5 design.v] \
    [file join $RTL_LIB lfsr8_6 design.v] \
    [file join $RTL_LIB lfsr9_7 design.v] \
    [file join $RTL_LIB lfsr10_8 design.v] \
    [file join $RTL_LIB lfsr11_9 design.v] \
    [file join $RTL_LIB lfsr12_10 design.v] \
    [file join $RTL_LIB lfsr13_11 design.v] \
    [file join $RTL_LIB lfsr14_12 design.v] \
    [file join $RTL_LIB lfsr15_13 design.v] \
    [file join $RTL_LIB lfsr16_14 design.v] \
    [file join $RTL_LIB acc2to8 design.v] \
    [file join $RTL_LIB acc2to10 design.v] \
    [file join $RTL_LIB acc2to12 design.v] \
    [file join $RTL_LIB acc2to14 design.v] \
    [file join $RTL_LIB acc2to16 design.v] \
    [file join $RTL_LIB acc3to8 design.v] \
    [file join $RTL_LIB acc3to10 design.v] \
    [file join $RTL_LIB acc3to12 design.v] \
    [file join $RTL_LIB acc3to14 design.v] \
    [file join $RTL_LIB acc3to16 design.v] \
    [file join $RTL_LIB acc4to8 design.v] \
    [file join $RTL_LIB acc4to10 design.v] \
    [file join $RTL_LIB acc4to12 design.v] \
    [file join $RTL_LIB acc4to14 design.v] \
    [file join $RTL_LIB acc4to16 design.v] \
    [file join $RTL_LIB acc5to8 design.v] \
    [file join $RTL_LIB acc5to10 design.v] \
    [file join $RTL_LIB acc5to12 design.v] \
    [file join $RTL_LIB acc5to14 design.v] \
    [file join $RTL_LIB acc5to16 design.v] \
    [file join $RTL_LIB acc6to8 design.v] \
    [file join $RTL_LIB acc6to10 design.v] \
    [file join $RTL_LIB acc6to12 design.v] \
    [file join $RTL_LIB acc6to14 design.v] \
    [file join $RTL_LIB acc6to16 design.v] \
    [file join $RTL_LIB acc7to8 design.v] \
    [file join $RTL_LIB acc7to10 design.v] \
    [file join $RTL_LIB acc7to12 design.v] \
    [file join $RTL_LIB acc7to14 design.v] \
    [file join $RTL_LIB acc7to16 design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b14.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b14.hwh]
}
puts "BATCH 14 DONE -> [file join $OUT system_b14.bit]"
