# Auto-generated by gen_bitstream.py  -  batch 0 (self-contained).
# Build:  vivado -mode batch -source build_b0.tcl
set BATCH   0
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b0]
file mkdir $OUT

create_project sys_b0 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b0.v] \
    [file join $RTL_LIB bitand2b design.v] \
    [file join $RTL_LIB bitor2b design.v] \
    [file join $RTL_LIB bitxor2b design.v] \
    [file join $RTL_LIB bitnand2b design.v] \
    [file join $RTL_LIB bitnor2b design.v] \
    [file join $RTL_LIB bitxnor2b design.v] \
    [file join $RTL_LIB bitand4b design.v] \
    [file join $RTL_LIB bitor4b design.v] \
    [file join $RTL_LIB bitxor4b design.v] \
    [file join $RTL_LIB bitnand4b design.v] \
    [file join $RTL_LIB bitnor4b design.v] \
    [file join $RTL_LIB bitxnor4b design.v] \
    [file join $RTL_LIB bitand6b design.v] \
    [file join $RTL_LIB bitor6b design.v] \
    [file join $RTL_LIB bitxor6b design.v] \
    [file join $RTL_LIB bitnand6b design.v] \
    [file join $RTL_LIB bitnor6b design.v] \
    [file join $RTL_LIB bitxnor6b design.v] \
    [file join $RTL_LIB bitand8b design.v] \
    [file join $RTL_LIB bitor8b design.v] \
    [file join $RTL_LIB bitxor8b design.v] \
    [file join $RTL_LIB bitnand8b design.v] \
    [file join $RTL_LIB bitnor8b design.v] \
    [file join $RTL_LIB bitxnor8b design.v] \
    [file join $RTL_LIB mod2_counter design.v] \
    [file join $RTL_LIB mod3_counter design.v] \
    [file join $RTL_LIB mod4_counter design.v] \
    [file join $RTL_LIB mod5_counter design.v] \
    [file join $RTL_LIB mod6_counter design.v] \
    [file join $RTL_LIB mod7_counter design.v] \
    [file join $RTL_LIB mod8_counter design.v] \
    [file join $RTL_LIB mod9_counter design.v] \
    [file join $RTL_LIB mod10_counter design.v] \
    [file join $RTL_LIB mod11_counter design.v] \
    [file join $RTL_LIB mod12_counter design.v] \
    [file join $RTL_LIB mod13_counter design.v] \
    [file join $RTL_LIB mod14_counter design.v] \
    [file join $RTL_LIB mod15_counter design.v] \
    [file join $RTL_LIB mod16_counter design.v] \
    [file join $RTL_LIB mod17_counter design.v] \
    [file join $RTL_LIB mod18_counter design.v] \
    [file join $RTL_LIB mod19_counter design.v] \
    [file join $RTL_LIB mod20_counter design.v] \
    [file join $RTL_LIB mod21_counter design.v] \
    [file join $RTL_LIB mod22_counter design.v] \
    [file join $RTL_LIB mod23_counter design.v] \
    [file join $RTL_LIB mod24_counter design.v] \
    [file join $RTL_LIB mod25_counter design.v] \
    [file join $RTL_LIB mod26_counter design.v] \
    [file join $RTL_LIB mod27_counter design.v] \
    [file join $RTL_LIB mod28_counter design.v] \
    [file join $RTL_LIB mod29_counter design.v] \
    [file join $RTL_LIB mod30_counter design.v] \
    [file join $RTL_LIB mod31_counter design.v] \
    [file join $RTL_LIB mod32_counter design.v] \
    [file join $RTL_LIB mod33_counter design.v] \
    [file join $RTL_LIB mod34_counter design.v] \
    [file join $RTL_LIB mod35_counter design.v] \
    [file join $RTL_LIB mod36_counter design.v] \
    [file join $RTL_LIB mod37_counter design.v] \
    [file join $RTL_LIB mod38_counter design.v] \
    [file join $RTL_LIB mod39_counter design.v] \
    [file join $RTL_LIB mod40_counter design.v] \
    [file join $RTL_LIB mod41_counter design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b0.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b0.hwh]
}
puts "BATCH 0 DONE -> [file join $OUT system_b0.bit]"
