# Auto-generated by gen_bitstream.py  -  batch 11 (self-contained).
# Build:  vivado -mode batch -source build_b11.tcl
set BATCH   11
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b11]
file mkdir $OUT

create_project sys_b11 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b11.v] \
    [file join $RTL_LIB thresh5_30 design.v] \
    [file join $RTL_LIB thresh6_32 design.v] \
    [file join $RTL_LIB thresh6_48 design.v] \
    [file join $RTL_LIB thresh6_16 design.v] \
    [file join $RTL_LIB thresh6_62 design.v] \
    [file join $RTL_LIB thresh7_64 design.v] \
    [file join $RTL_LIB thresh7_96 design.v] \
    [file join $RTL_LIB thresh7_32 design.v] \
    [file join $RTL_LIB thresh7_126 design.v] \
    [file join $RTL_LIB thresh8_128 design.v] \
    [file join $RTL_LIB thresh8_192 design.v] \
    [file join $RTL_LIB thresh8_64 design.v] \
    [file join $RTL_LIB thresh8_254 design.v] \
    [file join $RTL_LIB parity3 design.v] \
    [file join $RTL_LIB popcount3 design.v] \
    [file join $RTL_LIB reverse3 design.v] \
    [file join $RTL_LIB gray3 design.v] \
    [file join $RTL_LIB parity4 design.v] \
    [file join $RTL_LIB popcount4 design.v] \
    [file join $RTL_LIB reverse4 design.v] \
    [file join $RTL_LIB gray4 design.v] \
    [file join $RTL_LIB parity5 design.v] \
    [file join $RTL_LIB popcount5 design.v] \
    [file join $RTL_LIB reverse5 design.v] \
    [file join $RTL_LIB gray5 design.v] \
    [file join $RTL_LIB parity6 design.v] \
    [file join $RTL_LIB popcount6 design.v] \
    [file join $RTL_LIB reverse6 design.v] \
    [file join $RTL_LIB gray6 design.v] \
    [file join $RTL_LIB parity7 design.v] \
    [file join $RTL_LIB popcount7 design.v] \
    [file join $RTL_LIB reverse7 design.v] \
    [file join $RTL_LIB gray7 design.v] \
    [file join $RTL_LIB parity8 design.v] \
    [file join $RTL_LIB popcount8 design.v] \
    [file join $RTL_LIB reverse8 design.v] \
    [file join $RTL_LIB gray8 design.v] \
    [file join $RTL_LIB parity9 design.v] \
    [file join $RTL_LIB popcount9 design.v] \
    [file join $RTL_LIB reverse9 design.v] \
    [file join $RTL_LIB gray9 design.v] \
    [file join $RTL_LIB parity10 design.v] \
    [file join $RTL_LIB popcount10 design.v] \
    [file join $RTL_LIB reverse10 design.v] \
    [file join $RTL_LIB gray10 design.v] \
    [file join $RTL_LIB parity11 design.v] \
    [file join $RTL_LIB popcount11 design.v] \
    [file join $RTL_LIB reverse11 design.v] \
    [file join $RTL_LIB gray11 design.v] \
    [file join $RTL_LIB parity12 design.v] \
    [file join $RTL_LIB popcount12 design.v] \
    [file join $RTL_LIB reverse12 design.v] \
    [file join $RTL_LIB gray12 design.v] \
    [file join $RTL_LIB parity13 design.v] \
    [file join $RTL_LIB popcount13 design.v] \
    [file join $RTL_LIB reverse13 design.v] \
    [file join $RTL_LIB gray13 design.v] \
    [file join $RTL_LIB parity14 design.v] \
    [file join $RTL_LIB popcount14 design.v] \
    [file join $RTL_LIB reverse14 design.v] \
    [file join $RTL_LIB gray14 design.v] \
    [file join $RTL_LIB parity15 design.v] \
    [file join $RTL_LIB popcount15 design.v] \
    [file join $RTL_LIB reverse15 design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b11.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b11.hwh]
}
puts "BATCH 11 DONE -> [file join $OUT system_b11.bit]"
