# Auto-generated by gen_bitstream.py  -  batch 12 (self-contained).
# Build:  vivado -mode batch -source build_b12.tcl
set BATCH   12
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b12]
file mkdir $OUT

create_project sys_b12 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b12.v] \
    [file join $RTL_LIB gray15 design.v] \
    [file join $RTL_LIB parity16 design.v] \
    [file join $RTL_LIB popcount16 design.v] \
    [file join $RTL_LIB reverse16 design.v] \
    [file join $RTL_LIB gray16 design.v] \
    [file join $RTL_LIB neg_twos3b design.v] \
    [file join $RTL_LIB neg_ones3b design.v] \
    [file join $RTL_LIB neg_twos4b design.v] \
    [file join $RTL_LIB neg_ones4b design.v] \
    [file join $RTL_LIB neg_twos5b design.v] \
    [file join $RTL_LIB neg_ones5b design.v] \
    [file join $RTL_LIB neg_twos6b design.v] \
    [file join $RTL_LIB neg_ones6b design.v] \
    [file join $RTL_LIB neg_twos7b design.v] \
    [file join $RTL_LIB neg_ones7b design.v] \
    [file join $RTL_LIB neg_twos8b design.v] \
    [file join $RTL_LIB neg_ones8b design.v] \
    [file join $RTL_LIB neg_twos9b design.v] \
    [file join $RTL_LIB neg_ones9b design.v] \
    [file join $RTL_LIB neg_twos10b design.v] \
    [file join $RTL_LIB neg_ones10b design.v] \
    [file join $RTL_LIB neg_twos11b design.v] \
    [file join $RTL_LIB neg_ones11b design.v] \
    [file join $RTL_LIB neg_twos12b design.v] \
    [file join $RTL_LIB neg_ones12b design.v] \
    [file join $RTL_LIB neg_twos13b design.v] \
    [file join $RTL_LIB neg_ones13b design.v] \
    [file join $RTL_LIB neg_twos14b design.v] \
    [file join $RTL_LIB neg_ones14b design.v] \
    [file join $RTL_LIB neg_twos15b design.v] \
    [file join $RTL_LIB neg_ones15b design.v] \
    [file join $RTL_LIB neg_twos16b design.v] \
    [file join $RTL_LIB neg_ones16b design.v] \
    [file join $RTL_LIB abs3b design.v] \
    [file join $RTL_LIB abs4b design.v] \
    [file join $RTL_LIB abs5b design.v] \
    [file join $RTL_LIB abs6b design.v] \
    [file join $RTL_LIB abs7b design.v] \
    [file join $RTL_LIB abs8b design.v] \
    [file join $RTL_LIB abs9b design.v] \
    [file join $RTL_LIB abs10b design.v] \
    [file join $RTL_LIB abs11b design.v] \
    [file join $RTL_LIB abs12b design.v] \
    [file join $RTL_LIB halfswap4 design.v] \
    [file join $RTL_LIB halfswap6 design.v] \
    [file join $RTL_LIB halfswap8 design.v] \
    [file join $RTL_LIB halfswap10 design.v] \
    [file join $RTL_LIB halfswap12 design.v] \
    [file join $RTL_LIB halfswap14 design.v] \
    [file join $RTL_LIB halfswap16 design.v] \
    [file join $RTL_LIB prienc2 design.v] \
    [file join $RTL_LIB prienc3 design.v] \
    [file join $RTL_LIB prienc4 design.v] \
    [file join $RTL_LIB prienc5 design.v] \
    [file join $RTL_LIB prienc6 design.v] \
    [file join $RTL_LIB prienc7 design.v] \
    [file join $RTL_LIB prienc8 design.v] \
    [file join $RTL_LIB prienc9 design.v] \
    [file join $RTL_LIB prienc10 design.v] \
    [file join $RTL_LIB prienc11 design.v] \
    [file join $RTL_LIB prienc12 design.v] \
    [file join $RTL_LIB prienc13 design.v] \
    [file join $RTL_LIB prienc14 design.v] \
    [file join $RTL_LIB prienc15 design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b12.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b12.hwh]
}
puts "BATCH 12 DONE -> [file join $OUT system_b12.bit]"
