# Auto-generated by gen_bitstream.py  -  batch 3 (self-contained).
# Build:  vivado -mode batch -source build_b3.tcl
set BATCH   3
set PART    "xc7z020clg400-1"     ;# PYNQ-Z2 (Zynq-7020)
set CLK_MHZ 100
# Repo root = two levels up from this script (rtl/batches/ -> repo root).
set ROOT    [file normalize [file join [file dirname [info script]] .. ..]]
set RTL_LIB [file join $ROOT rtl_library]
set OUT     [file join $ROOT rtl batches out_b3]
file mkdir $OUT

create_project sys_b3 [file join $OUT proj] -part $PART -force
add_files [list \
    [file join $ROOT rtl la_axi_wide.v] \
    [file join $ROOT rtl batches dut_top_b3.v] \
    [file join $RTL_LIB updown5b design.v] \
    [file join $RTL_LIB updown6b design.v] \
    [file join $RTL_LIB updown7b design.v] \
    [file join $RTL_LIB updown8b design.v] \
    [file join $RTL_LIB updown9b design.v] \
    [file join $RTL_LIB updown10b design.v] \
    [file join $RTL_LIB updown11b design.v] \
    [file join $RTL_LIB updown12b design.v] \
    [file join $RTL_LIB updown13b design.v] \
    [file join $RTL_LIB updown14b design.v] \
    [file join $RTL_LIB updown15b design.v] \
    [file join $RTL_LIB step2_cnt4b design.v] \
    [file join $RTL_LIB step3_cnt4b design.v] \
    [file join $RTL_LIB step4_cnt4b design.v] \
    [file join $RTL_LIB step5_cnt4b design.v] \
    [file join $RTL_LIB step6_cnt4b design.v] \
    [file join $RTL_LIB step7_cnt4b design.v] \
    [file join $RTL_LIB step8_cnt4b design.v] \
    [file join $RTL_LIB step9_cnt4b design.v] \
    [file join $RTL_LIB step10_cnt4b design.v] \
    [file join $RTL_LIB step11_cnt4b design.v] \
    [file join $RTL_LIB step12_cnt4b design.v] \
    [file join $RTL_LIB step13_cnt4b design.v] \
    [file join $RTL_LIB step15_cnt4b design.v] \
    [file join $RTL_LIB step2_cnt5b design.v] \
    [file join $RTL_LIB step3_cnt5b design.v] \
    [file join $RTL_LIB step4_cnt5b design.v] \
    [file join $RTL_LIB step5_cnt5b design.v] \
    [file join $RTL_LIB step6_cnt5b design.v] \
    [file join $RTL_LIB step7_cnt5b design.v] \
    [file join $RTL_LIB step8_cnt5b design.v] \
    [file join $RTL_LIB step9_cnt5b design.v] \
    [file join $RTL_LIB step10_cnt5b design.v] \
    [file join $RTL_LIB step11_cnt5b design.v] \
    [file join $RTL_LIB step12_cnt5b design.v] \
    [file join $RTL_LIB step13_cnt5b design.v] \
    [file join $RTL_LIB step15_cnt5b design.v] \
    [file join $RTL_LIB step2_cnt6b design.v] \
    [file join $RTL_LIB step3_cnt6b design.v] \
    [file join $RTL_LIB step4_cnt6b design.v] \
    [file join $RTL_LIB step5_cnt6b design.v] \
    [file join $RTL_LIB step6_cnt6b design.v] \
    [file join $RTL_LIB step7_cnt6b design.v] \
    [file join $RTL_LIB step8_cnt6b design.v] \
    [file join $RTL_LIB step9_cnt6b design.v] \
    [file join $RTL_LIB step10_cnt6b design.v] \
    [file join $RTL_LIB step11_cnt6b design.v] \
    [file join $RTL_LIB step12_cnt6b design.v] \
    [file join $RTL_LIB step13_cnt6b design.v] \
    [file join $RTL_LIB step15_cnt6b design.v] \
    [file join $RTL_LIB step2_cnt7b design.v] \
    [file join $RTL_LIB step3_cnt7b design.v] \
    [file join $RTL_LIB step4_cnt7b design.v] \
    [file join $RTL_LIB step5_cnt7b design.v] \
    [file join $RTL_LIB step6_cnt7b design.v] \
    [file join $RTL_LIB step7_cnt7b design.v] \
    [file join $RTL_LIB step8_cnt7b design.v] \
    [file join $RTL_LIB step9_cnt7b design.v] \
    [file join $RTL_LIB step10_cnt7b design.v] \
    [file join $RTL_LIB step11_cnt7b design.v] \
    [file join $RTL_LIB step12_cnt7b design.v] \
    [file join $RTL_LIB step13_cnt7b design.v] \
    [file join $RTL_LIB step15_cnt7b design.v] \
    [file join $RTL_LIB step2_cnt8b design.v] ]
update_compile_order -fileset sources_1

create_bd_design "system"
# --- Zynq PS7 (same board preset automation as the project's synth flow) ---
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} \
    [get_bd_cells ps7]
set_property -dict [list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ $CLK_MHZ] \
    [get_bd_cells ps7]

# --- Logic analyzer (AXI-Lite slave) + the batch DUT mux, as RTL modules ---
create_bd_cell -type module -reference la_axi_wide la0
create_bd_cell -type module -reference dut_top      dut0

# Auto-build AXI interconnect + reset and connect clocks to la0/S_AXI.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/ps7/M_AXI_GP0" Clk "Auto"} \
    [get_bd_intf_pins la0/S_AXI]

# Probe/sel between LA and DUT; share the AXI clock/reset with the DUT.
connect_bd_net [get_bd_pins la0/sel]    [get_bd_pins dut0/sel]
connect_bd_net [get_bd_pins la0/probe]  [get_bd_pins dut0/probe]
connect_bd_net [get_bd_pins dut0/clk]   [get_bd_pins la0/S_AXI_ACLK]
connect_bd_net [get_bd_pins dut0/rst_n] [get_bd_pins la0/S_AXI_ARESETN]

assign_bd_address
validate_bd_design
save_bd_design

make_wrapper -files [get_files system.bd] -top -force
add_files -norecurse [glob \
    [file join $OUT proj *.gen sources_1 bd system hdl system_wrapper.v] \
    [file join $OUT proj *.srcs sources_1 bd system hdl system_wrapper.v]]
set_property top system_wrapper [current_fileset]

launch_runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# Collect artifacts PYNQ needs (.bit + .hwh).
file copy -force [glob [file join $OUT proj *.runs impl_1 system_wrapper.bit]] \
    [file join $OUT system_b3.bit]
set hwh [glob -nocomplain \
    [file join $OUT proj *.gen sources_1 bd system hw_handoff system.hwh] \
    [file join $OUT proj *.srcs sources_1 bd system hw_handoff system.hwh]]
if {$hwh ne ""} {
    file copy -force [lindex $hwh 0] [file join $OUT system_b3.hwh]
}
puts "BATCH 3 DONE -> [file join $OUT system_b3.bit]"
