`timescale 1ns/1ps
// Auto-generated by gen_bitstream.py  -  batch 15 (44 DUTs).
// Local sel[5:0] selects which DUT drives probe[15:0].
module dut_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [5:0] sel,
    output reg  [15:0] probe
);
    // free-running counter -- deterministic stimulus source (matches scorer tb)
    reg [31:0] cnt;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) cnt <= 32'b0;
        else        cnt <= cnt + 1'b1;

    wire [7:0] d0_acc;
    wire [9:0] d1_acc;
    wire [11:0] d2_acc;
    wire [13:0] d3_acc;
    wire [15:0] d4_acc;
    wire [7:0] d5_acc;
    wire [9:0] d6_acc;
    wire [11:0] d7_acc;
    wire [13:0] d8_acc;
    wire [15:0] d9_acc;
    wire [7:0] d10_acc;
    wire [9:0] d11_acc;
    wire [11:0] d12_acc;
    wire [13:0] d13_acc;
    wire [15:0] d14_acc;
    wire [7:0] d15_acc;
    wire [9:0] d16_acc;
    wire [11:0] d17_acc;
    wire [13:0] d18_acc;
    wire [15:0] d19_acc;
    wire [9:0] d20_acc;
    wire [11:0] d21_acc;
    wire [13:0] d22_acc;
    wire [15:0] d23_acc;
    wire [11:0] d24_acc;
    wire [13:0] d25_acc;
    wire [15:0] d26_acc;
    wire [13:0] d27_acc;
    wire [15:0] d28_acc;
    wire [15:0] d29_acc;
    wire [3:0] d30_acc;
    wire [3:0] d31_acc;
    wire [4:0] d32_acc;
    wire [4:0] d33_acc;
    wire [5:0] d34_acc;
    wire [5:0] d35_acc;
    wire [6:0] d36_acc;
    wire [6:0] d37_acc;
    wire [7:0] d38_acc;
    wire [7:0] d39_acc;
    wire [9:0] d40_acc;
    wire [9:0] d41_acc;
    wire [11:0] d42_acc;
    wire [11:0] d43_acc;

    acc8to8 u_d0 ( .clk(clk), .rst_n(rst_n), .data(cnt[7:0]), .acc(d0_acc) );
    acc8to10 u_d1 ( .clk(clk), .rst_n(rst_n), .data(cnt[7:0]), .acc(d1_acc) );
    acc8to12 u_d2 ( .clk(clk), .rst_n(rst_n), .data(cnt[7:0]), .acc(d2_acc) );
    acc8to14 u_d3 ( .clk(clk), .rst_n(rst_n), .data(cnt[7:0]), .acc(d3_acc) );
    acc8to16 u_d4 ( .clk(clk), .rst_n(rst_n), .data(cnt[7:0]), .acc(d4_acc) );
    mac2_8b u_d5 ( .clk(clk), .rst_n(rst_n), .a(cnt[1:0]), .b(cnt[3:2]), .acc(d5_acc) );
    mac2_10b u_d6 ( .clk(clk), .rst_n(rst_n), .a(cnt[1:0]), .b(cnt[3:2]), .acc(d6_acc) );
    mac2_12b u_d7 ( .clk(clk), .rst_n(rst_n), .a(cnt[1:0]), .b(cnt[3:2]), .acc(d7_acc) );
    mac2_14b u_d8 ( .clk(clk), .rst_n(rst_n), .a(cnt[1:0]), .b(cnt[3:2]), .acc(d8_acc) );
    mac2_16b u_d9 ( .clk(clk), .rst_n(rst_n), .a(cnt[1:0]), .b(cnt[3:2]), .acc(d9_acc) );
    mac3_8b u_d10 ( .clk(clk), .rst_n(rst_n), .a(cnt[2:0]), .b(cnt[5:3]), .acc(d10_acc) );
    mac3_10b u_d11 ( .clk(clk), .rst_n(rst_n), .a(cnt[2:0]), .b(cnt[5:3]), .acc(d11_acc) );
    mac3_12b u_d12 ( .clk(clk), .rst_n(rst_n), .a(cnt[2:0]), .b(cnt[5:3]), .acc(d12_acc) );
    mac3_14b u_d13 ( .clk(clk), .rst_n(rst_n), .a(cnt[2:0]), .b(cnt[5:3]), .acc(d13_acc) );
    mac3_16b u_d14 ( .clk(clk), .rst_n(rst_n), .a(cnt[2:0]), .b(cnt[5:3]), .acc(d14_acc) );
    mac4_8b u_d15 ( .clk(clk), .rst_n(rst_n), .a(cnt[3:0]), .b(cnt[7:4]), .acc(d15_acc) );
    mac4_10b u_d16 ( .clk(clk), .rst_n(rst_n), .a(cnt[3:0]), .b(cnt[7:4]), .acc(d16_acc) );
    mac4_12b u_d17 ( .clk(clk), .rst_n(rst_n), .a(cnt[3:0]), .b(cnt[7:4]), .acc(d17_acc) );
    mac4_14b u_d18 ( .clk(clk), .rst_n(rst_n), .a(cnt[3:0]), .b(cnt[7:4]), .acc(d18_acc) );
    mac4_16b u_d19 ( .clk(clk), .rst_n(rst_n), .a(cnt[3:0]), .b(cnt[7:4]), .acc(d19_acc) );
    mac5_10b u_d20 ( .clk(clk), .rst_n(rst_n), .a(cnt[4:0]), .b(cnt[9:5]), .acc(d20_acc) );
    mac5_12b u_d21 ( .clk(clk), .rst_n(rst_n), .a(cnt[4:0]), .b(cnt[9:5]), .acc(d21_acc) );
    mac5_14b u_d22 ( .clk(clk), .rst_n(rst_n), .a(cnt[4:0]), .b(cnt[9:5]), .acc(d22_acc) );
    mac5_16b u_d23 ( .clk(clk), .rst_n(rst_n), .a(cnt[4:0]), .b(cnt[9:5]), .acc(d23_acc) );
    mac6_12b u_d24 ( .clk(clk), .rst_n(rst_n), .a(cnt[5:0]), .b(cnt[11:6]), .acc(d24_acc) );
    mac6_14b u_d25 ( .clk(clk), .rst_n(rst_n), .a(cnt[5:0]), .b(cnt[11:6]), .acc(d25_acc) );
    mac6_16b u_d26 ( .clk(clk), .rst_n(rst_n), .a(cnt[5:0]), .b(cnt[11:6]), .acc(d26_acc) );
    mac7_14b u_d27 ( .clk(clk), .rst_n(rst_n), .a(cnt[6:0]), .b(cnt[13:7]), .acc(d27_acc) );
    mac7_16b u_d28 ( .clk(clk), .rst_n(rst_n), .a(cnt[6:0]), .b(cnt[13:7]), .acc(d28_acc) );
    mac8_16b u_d29 ( .clk(clk), .rst_n(rst_n), .a(cnt[7:0]), .b(cnt[15:8]), .acc(d29_acc) );
    rmax4b u_d30 ( .clk(clk), .rst_n(rst_n), .x(cnt[3:0]), .acc(d30_acc) );
    rmin4b u_d31 ( .clk(clk), .rst_n(rst_n), .x(cnt[3:0]), .acc(d31_acc) );
    rmax5b u_d32 ( .clk(clk), .rst_n(rst_n), .x(cnt[4:0]), .acc(d32_acc) );
    rmin5b u_d33 ( .clk(clk), .rst_n(rst_n), .x(cnt[4:0]), .acc(d33_acc) );
    rmax6b u_d34 ( .clk(clk), .rst_n(rst_n), .x(cnt[5:0]), .acc(d34_acc) );
    rmin6b u_d35 ( .clk(clk), .rst_n(rst_n), .x(cnt[5:0]), .acc(d35_acc) );
    rmax7b u_d36 ( .clk(clk), .rst_n(rst_n), .x(cnt[6:0]), .acc(d36_acc) );
    rmin7b u_d37 ( .clk(clk), .rst_n(rst_n), .x(cnt[6:0]), .acc(d37_acc) );
    rmax8b u_d38 ( .clk(clk), .rst_n(rst_n), .x(cnt[7:0]), .acc(d38_acc) );
    rmin8b u_d39 ( .clk(clk), .rst_n(rst_n), .x(cnt[7:0]), .acc(d39_acc) );
    rmax10b u_d40 ( .clk(clk), .rst_n(rst_n), .x(cnt[9:0]), .acc(d40_acc) );
    rmin10b u_d41 ( .clk(clk), .rst_n(rst_n), .x(cnt[9:0]), .acc(d41_acc) );
    rmax12b u_d42 ( .clk(clk), .rst_n(rst_n), .x(cnt[11:0]), .acc(d42_acc) );
    rmin12b u_d43 ( .clk(clk), .rst_n(rst_n), .x(cnt[11:0]), .acc(d43_acc) );

    always @(*) begin
        case (sel)
            6'd0: probe = {8'b0, d0_acc};
            6'd1: probe = {6'b0, d1_acc};
            6'd2: probe = {4'b0, d2_acc};
            6'd3: probe = {2'b0, d3_acc};
            6'd4: probe = d4_acc[15:0];
            6'd5: probe = {8'b0, d5_acc};
            6'd6: probe = {6'b0, d6_acc};
            6'd7: probe = {4'b0, d7_acc};
            6'd8: probe = {2'b0, d8_acc};
            6'd9: probe = d9_acc[15:0];
            6'd10: probe = {8'b0, d10_acc};
            6'd11: probe = {6'b0, d11_acc};
            6'd12: probe = {4'b0, d12_acc};
            6'd13: probe = {2'b0, d13_acc};
            6'd14: probe = d14_acc[15:0];
            6'd15: probe = {8'b0, d15_acc};
            6'd16: probe = {6'b0, d16_acc};
            6'd17: probe = {4'b0, d17_acc};
            6'd18: probe = {2'b0, d18_acc};
            6'd19: probe = d19_acc[15:0];
            6'd20: probe = {6'b0, d20_acc};
            6'd21: probe = {4'b0, d21_acc};
            6'd22: probe = {2'b0, d22_acc};
            6'd23: probe = d23_acc[15:0];
            6'd24: probe = {4'b0, d24_acc};
            6'd25: probe = {2'b0, d25_acc};
            6'd26: probe = d26_acc[15:0];
            6'd27: probe = {2'b0, d27_acc};
            6'd28: probe = d28_acc[15:0];
            6'd29: probe = d29_acc[15:0];
            6'd30: probe = {12'b0, d30_acc};
            6'd31: probe = {12'b0, d31_acc};
            6'd32: probe = {11'b0, d32_acc};
            6'd33: probe = {11'b0, d33_acc};
            6'd34: probe = {10'b0, d34_acc};
            6'd35: probe = {10'b0, d35_acc};
            6'd36: probe = {9'b0, d36_acc};
            6'd37: probe = {9'b0, d37_acc};
            6'd38: probe = {8'b0, d38_acc};
            6'd39: probe = {8'b0, d39_acc};
            6'd40: probe = {6'b0, d40_acc};
            6'd41: probe = {6'b0, d41_acc};
            6'd42: probe = {4'b0, d42_acc};
            6'd43: probe = {4'b0, d43_acc};
            default: probe = 16'b0;
        endcase
    end
endmodule
