#!/usr/bin/env python3
"""Render completed post-primary evidence without altering frozen studies.

Validation is read-only. Only paper/generated/revision_* outputs are written.
Every input result is checked by its existing independent validator first.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper/generated"
ARTIFACT = "artifact_extension_results.json"
CLOSURE = "timing_closure_candidate_v7/results/pilot_gate.json"
VERILOG = ("verilogeval_rf_extension_v3/results/validated_20260830/"
           "comparison_recovery_gpu1_20260830/comparison.json")


def read(path):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def validate():
    # Require a pre-existing gate: the closure validator must not create one.
    if not (ROOT / CLOSURE).is_file():
        raise RuntimeError("completed setup-closure pilot gate is missing")
    for command in (
        ["analyze_artifact_extension.py", "--check"],
        ["timing_closure_candidate_v7/validate.py", "--scope", "pilot"],
        ["verilogeval_rf_extension_v3/verify_archive.py"],
    ):
        result = subprocess.run([sys.executable, *command], cwd=ROOT,
                                capture_output=True, text=True)
        if result.returncode:
            raise RuntimeError(result.stdout + result.stderr)


def outputs():
    validate()
    claims, inputs = {}, {}

    def source(path):
        # All revision-ledger inputs are text; match Git's LF representation.
        raw = (ROOT / path).read_bytes().replace(b"\r\n", b"\n")
        inputs[path] = hashlib.sha256(raw).hexdigest()
        return f"{path}:1-{len(raw.splitlines())}"

    def add(name, value, path, method, unit="", digits=2):
        display = str(value) if isinstance(value, (str, int)) else f"{value:.{digits}f}"
        claims[name] = dict(value=value, display=display, unit=unit,
                            method=method, sources=[source(path)])
        return r"\revisionclaim{" + name + "}"

    def table(caption, label, columns, header, rows, note=""):
        return ("% AUTO-GENERATED by paper/make_revision_evidence.py.\n"
                "\\begin{table}[t]\n\\centering\n\\caption{" + caption + "}\n"
                "\\label{" + label + "}\n\\small\n\\begin{tabular}{@{}" + columns + "@{}}\n"
                "\\toprule\n" + header + " \\\\\n\\midrule\n" +
                "\n".join(" & ".join(row) + r" \\" for row in rows) +
                "\n\\bottomrule\n\\end{tabular}\n" + note + "\n\\end{table}\n")

    artifact = read(ARTIFACT)
    rows = []
    for arm, name in (("sft", "Sft"), ("rf", "Rf"), ("mlp", "Mlp"),
                      ("correctness", "Correctness")):
        row = artifact["decomposition"]["arms"][arm]["all"]
        q = add(name + "Correctness", 100 * row["q_correct"], ARTIFACT,
                "All-draw oracle pass fraction multiplied by 100", "%")
        mu = add(name + "Conditional", row["mu_fmax_given_correct_mhz"], ARTIFACT,
                 "Pooled correct-draw mean; implementation failures remain zero", "MHz")
        f = add(name + "Penalized", row["penalized_fmax_mhz"], ARTIFACT,
                "Equal-budget all-design failure-penalized mean", "MHz")
        rows.append([{"sft": "SFT", "rf": "RF", "mlp": "MLP",
                      "correctness": "Correctness only"}[arm], q, mu, f])
    rendered = {OUT / "revision_table_decomposition.tex": table(
        "Post-primary decomposition on the complete sealed draw set. Conditional "
        "frequency pools correct draws, including zero-valued implementation failures.",
        "tab:decomposition", "lrrr", r"Policy & $q$ (\%) & $\mu$ (MHz) & $q\mu$ (MHz)", rows)}

    best = artifact["best_of_n"]["scopes"]["all"]
    crossing = best["rf_one_draw_sft_best_of_n_crossing"]
    for name, key in (("SelectorLowerN", "lower_n"), ("SelectorUpperN", "upper_n"),
                      ("SelectorLowerFmax", "lower_fmax_mhz"),
                      ("SelectorUpperFmax", "upper_fmax_mhz")):
        add(name, crossing[key], ARTIFACT, "Frozen-support perfect-selector crossing")
    cost = best["cost_at_crossing_upper_n"]
    for name, key in (
        ("SelectorStreams", "oracle_simulation_streams_per_design"),
        ("SelectorRawImplementations", "expected_raw_correct_draws_requiring_implementation_without_cache_per_design"),
        ("SelectorCachedImplementations", "expected_content_deduplicated_correct_implementations_per_design"),
    ):
        add(name, cost[key], ARTIFACT, "Expected workload at integer crossing; not wall-clock time", digits=3)

    gate = read(CLOSURE)
    if gate["verdict"] != "PASS":
        raise RuntimeError("setup-closure pilot did not pass its frozen gate")
    add("ClosureCandidateCount", gate["completed_candidates"], CLOSURE, "Completed pilot candidates")
    add("ClosureVersion", gate["vivado_version"], CLOSURE, "Pilot Vivado version")
    for name, key, multiplier, digits in (
        ("ClosureRho", "spearman_rho", 1, 3),
        ("ClosureMedianSmape", "median_smape", 100, 2),
        ("ClosureSignReversals", "sign_reversals", 1, 0),
        ("ClosureNonTiedPairs", "non_tied_pairs", 1, 0),
    ):
        add(name, gate["metrics"][key] * multiplier, CLOSURE,
            "Validated pilot metric; SMAPE expressed in percent", digits=digits)
    add("ClosureWorstSmape", 100 * max(gate["metrics"]["candidate_smape"]), CLOSURE,
        "Maximum, not median, candidate symmetric percentage error", "%")
    candidates = {}
    for entry in gate["generated_from"]:
        path = entry["path"]
        if path.endswith("/closure_result.json"):
            row = read(path)
            candidates[(row["design"], row["arm"])] = (row, path)
    rows = []
    for index, pair in enumerate(gate["metrics"]["pairs"]):
        design = pair["design"]
        letter = chr(ord("A") + index)
        cells = [design.replace("_", r"\_")]
        for arm in ("sft", "rf"):
            row, path = candidates[(design, arm)]
            for label, key in (("Original", "old_fmax_mhz"), ("Setup", "closure_fmax_mhz")):
                cells.append(add("Closure" + letter + arm.title() + label, row[key], path,
                                 "Original WNS-derived or conservative setup-passing bracket endpoint", "MHz"))
        rows.append(cells)
    rendered[OUT / "revision_table_closure.tex"] = table(
        "Descriptive setup-closure sensitivity (MHz). Original: frozen WNS-derived "
        "value. Setup: conservative passing endpoint under the pilot flow.",
        "tab:setup-closure", "lrrrr",
        r"Design & SFT orig. & SFT setup & RF orig. & RF setup", rows)

    verilog = read(VERILOG)
    add("VerilogProblems", verilog["problem_count"], VERILOG, "Matched official benchmark problems")
    add("VerilogSamples", verilog["n_samples_per_policy_problem"], VERILOG,
        "Draws per checkpoint per problem")
    rows = []
    for arm, label, prefix in (("sft", "SFT", "Sft"), ("rf_s1", "RF seed one", "RfOne"),
                               ("rf_s2", "RF seed two", "RfTwo")):
        value = add("Verilog" + prefix, 100 * verilog["policies"][arm]["pass_at_1"],
                    VERILOG, "Matched problem-average pass-at-one multiplied by 100", "%")
        rows.append([label, value])
    contrast = verilog["paired_pass_at_1"]["rf_seed_mean_minus_sft"]
    for name, value in (("VerilogDelta", contrast["estimate"]),
                        ("VerilogCiLow", contrast["ci95"][0]),
                        ("VerilogCiHigh", contrast["ci95"][1])):
        add(name, 100 * value, VERILOG, "Paired problem-level RF-seed-mean minus SFT; percentage points", "pp")
    rendered[OUT / "revision_table_verilog.tex"] = table(
        "Matched post-primary general-RTL evaluation. Each checkpoint uses the same "
        "benchmark, generation settings, and draw budget.",
        "tab:matched-verilog", "lr", r"Checkpoint & Pass-at-one (\%)", rows)

    # Read the actual function defaults without importing the simulation stack.
    tree = ast.parse((ROOT / "oracle.py").read_text(encoding="utf-8"))
    defaults = {}
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in ("align_score", "score"):
            defaults[node.name] = {arg.arg: ast.literal_eval(value) for arg, value in
                                   zip(node.args.args[-len(node.args.defaults):], node.args.defaults)}
    for name, value in (("OracleMaxLatency", defaults["align_score"]["max_lat"]),
                        ("OracleWarmup", defaults["align_score"]["warmup"]),
                        ("OracleThreshold", defaults["score"]["pass_thresh"])):
        add(name, value, "oracle.py", "Frozen oracle function default", digits=3)

    ledger = dict(schema="paper_revision_claims/1", evidence_status="completed post-primary; no new experiments",
                  inputs_sha256=inputs, claims=claims)
    rendered[OUT / "revision_claims.json"] = json.dumps(ledger, indent=2) + "\n"
    tex = ["% AUTO-GENERATED by paper/make_revision_evidence.py. DO NOT EDIT.",
           r"\providecommand{\revisionclaim}[1]{\csname RevisionClaim#1\endcsname}"]
    for name, record in claims.items():
        tex += ["% SOURCE " + "; ".join(record["sources"]),
                r"\expandafter\def\csname RevisionClaim" + name + r"\endcsname{" + record["display"] + "}"]
    rendered[OUT / "revision_claims.tex"] = "\n".join(tex) + "\n"
    return rendered


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        for path, expected in outputs().items():
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                    raise RuntimeError(f"missing or stale {path.relative_to(ROOT)}")
            else:
                path.write_text(expected, encoding="utf-8", newline="\n")
        print("PASS manuscript revision evidence: validated inputs and current claims/tables")
    except (OSError, ValueError, KeyError, RuntimeError) as error:
        print(f"FAIL manuscript revision evidence: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
